### ISSUE TITLE
Pending requests although space got changed to being open to everyone

### ISSUE THREAD

**Issue by Dr-Electron** [soonlabs/soonaverse-dao#116]
**Describe the bug**

I had a space which needed approval for every member. After having still some pending requests I changed the space to be open for everyone. But now I still have 6 pending requests it seems. Not sure if this all is related.
If I again close the space I don't see pending requests tho 🤔 

**To Reproduce**

1. Create space which needs approval for every new member
2. Get some pending requests
3. Change the settings for the space to be open for everyone
4. Still pending requests

**Expected behavior**

Once switched to the open setup all pending request should get approved automatically

**Comment by adamkundrat** [comment]
This has been fixed. Counter was not resetting correctly. Thank you for reporting.
