### ISSUE TITLE
Add localization for 6 top languages 

### ISSUE THREAD

**Issue by antonionardella** [soonlabs/soonaverse-dao#120]
**Is your feature request related to a problem? Please describe.**
It's hard to remember how to read the date

**Describe the solution you'd like**
Please enable different date settings like e.g.
DD-MM-YYYY
or the ISO standard
YYYY-MM-DD
https://www.w3.org/QA/Tips/iso-date

**Describe alternatives you've considered**

**Additional context**
Thank you!

**Comment by adamkundrat** [comment]
We've not loaded locale's into the app. We'll get this fixed in few days. Thank you for reporting.

**Comment by adamkundrat** [comment]
Let's start with:
- EN
- DE
- IT
- FR
- SP
- Turkish

**Comment by adamkundrat** [comment]
Enabled date formatting for above languages. Date should be correct based on location. 

Added initial localization file for those languages. We will start to work on translations for above languages over next few sprints.

**Comment by adamkundrat** [comment]
related issue: https://github.com/soonlabs/soonaverse-dao/issues/196
