### ISSUE TITLE
Time difference make it look like it's pending even thought start time already passed

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#125]
**Describe the bug**
Once a vote is issued it shows a time, when the vote should start. In my computer the time is 9:11 p.m. while the vote should start actually at 8:39 pm.
This could be misleading or confusing

Check the attachment. 
![Time issue difference](https://user-images.githubusercontent.com/65918138/144762430-f1c8d290-9fd5-43e9-8945-a077bc42b5c4.PNG)

**Comment by adamkundrat** [comment]
This has been tweaked in upcoming release. Must be re-tested
