### ISSUE TITLE
Loading site was very very slow.

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#126]
**Describe the bug**
If you want to join the site from Europe it is very hard to load and get the content. It was nearly impossible to get an avatar or enter spaces. Using a VPN through a server in the US did the job. Site is now loading very fast and the site works smooth. Putting more weight on the EU servers would be a benefit.

**Comment by adamkundrat** [comment]
Let me know if you find out what was the issue with your browser. Thank you for investigating this.
