### ISSUE TITLE
Inconsistant behavior loading 'Members' tab in a space

### ISSUE THREAD

**Issue by SeanTMartin** [soonlabs/soonaverse-dao#132]
**Describe the bug**
Seemingly at random, clicking the members tab for the first time or refreshing the members tab (anything that causes the members tab to have to load all the members again) results in a different thing displaying. It will either display 'Loading...' during the load OR causes the user to be loaded as the only member until all others are loaded. Display seems to be normal after load in either case.

**To Reproduce**
1. Go to any space with high number of members (Iota welcome dao should work)
2. Click on 'Members'
3. Refresh a bunch or tab back and forth to force reloads of 'Members'.
4. See inconsistant behavior

**Expected behavior**
'Loading...' Should always be displayed during loading rather than sometimes the user's member entry being loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/38050901/144779931-563c86c8-86ef-4b33-86ea-c0116ad1f5c5.png)
![image](https://user-images.githubusercontent.com/38050901/144779978-ae44344e-c460-42f8-b9dd-d8df4f326027.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by adamkundrat** [comment]
Yeah I noticed some performance inconsistencies here. I'll investigate.

**Comment by Phyloiota** [comment]
confirming this, it directly shows the guardian upon opening the page, but needs around 2 seconds to load the member list

**Comment by adamkundrat** [comment]
Yep it's just a big list in some cases and we need improve our indexing there. We never had soo many members:)

We're also working on #12 which should improve experience.

**Comment by adamkundrat** [comment]
Lot of improvements have been done here. This is ready for testing in edge
