### ISSUE TITLE
Awards showing participated and issued. It should have filter.

### ISSUE THREAD

**Issue by callmeworden** [soonlabs/soonaverse-dao#140]
I never awarded the account in the snippy below a DeFi Academy award, but it's still showing up in their profile (I know it doesn't say complete, but it still probably shouldn't be here since I don't have the ability to reject a pending participant and it'll forever be in their profile forever because of that). 

![image](https://user-images.githubusercontent.com/78708402/144955031-023b018f-b8f0-4b50-86be-056a1befdebc.png)

**Comment by adamkundrat** [comment]
Will add a filter here, participated / issued badges.

**Comment by adamkundrat** [comment]
filter added and available in edge env.
