### ISSUE TITLE
IOTA Donation Address Field

### ISSUE THREAD

**Issue by hassping** [soonlabs/soonaverse-dao#141]
Please add a field specific for IOTA donation addresses

![image](https://user-images.githubusercontent.com/51343893/144955875-14f2d106-5415-46ad-9001-1215a4c88ad2.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adamkundrat** [comment]
we now have address field on both spaces/members :)
