### ISSUE TITLE
Cannot open spaces in new tab

### ISSUE THREAD

**Issue by begonaalvarezd** [soonlabs/soonaverse-dao#148]
**Describe the bug**

In the `Discover` view, because there is no `a` element in the `wen-space-card`s, you cannot open the spaces in a new tab. I think it would be cool adding an `a` or something similar to allow opening in new tab, at least is how I like browsing 😅 

**To Reproduce**
1. Go to https://soonaverse.com/
2. Click on **discover**
3. On the discover page, try to open any of the spaces in a new tab: right click `open in new tab` doesnt appear, ctrl(cmd)+click open in the same tab, custom shortcuts to open in a new tab also dont work

**Expected behavior**

Be able to open in a new tab

**Screenshots**

Playground view 
![image](https://user-images.githubusercontent.com/3624944/145038665-864bf83e-3a00-440d-918e-56c190cf8cff.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 94.0.4606.61 (Official Build) (64-bit)

**Comment by begonaalvarezd** [comment]
Same happens in the award cards `wen-award-card`

**Comment by adamkundrat** [comment]
I agree this is indeed very annoying. Will fix this.

**Comment by adamkundrat** [comment]
Fixed cards:
- wen-space-card
- wen-award-card
- wen-member-card
- wen-proposal-card

Will be available in edge.soonaverse.com for testing. Will be released next week.
