### ISSUE TITLE
The Reputation Graph in Personal Profile is a smooth line rather than a step function.

### ISSUE THREAD

**Issue by dumdave** [soonlabs/soonaverse-dao#166]
**Describe the bug**
My awards are something like 2 points, 2, 20, 20, 500. But I get a smooth graph. It does not feel right for this kind of data.

**Comment by adamkundrat** [comment]
Thanks for reporting. Yeah I noticed as well the graph is misbehaving once there is more data. I'll add this to current sprint and try to improve it.

**Comment by adamkundrat** [comment]
@Gundavri - please re-search and propose better graph library we can use. This will be needed on members profile and price history of NFT.

Ideally supporting rxjs streams.
