### ISSUE TITLE
Bug or suggestion. Under Awards in Personal Profile awards you have been given show as 'available'.

### ISSUE THREAD

**Issue by dumdave** [soonlabs/soonaverse-dao#168]
**Describe the bug**
Having won an Award it still shows under Awards as available - which makes you think that you have not got it. Needs to show 'awarded' or '1 awarded' if it is possible to win more than 1.

**Comment by frnfa** [comment]
thanks @dumdave, great suggestion

**Comment by frnfa** [comment]
@adamkundrat can you add filters under Profile - Awards tab
- Pending
- Awarded / Issued

**Comment by adamkundrat** [comment]
This has been fixed and it'll come out today/tomorrow.
