### ISSUE TITLE
Creating big amounts of awards does not work

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#169]
Tried to create 500 awards with 10 XP each, but it is not accepted if I put in 5000 XP for 500 awards, the XP field gets framed red as soon as I click "create award"

<img width="337" alt="image" src="https://user-images.githubusercontent.com/77154511/145121526-b5f93517-ef56-493a-acd0-d5b63caf632a.png">

**Comment by adamkundrat** [comment]
We need to improve error reporting here. Thanks for reporting. At the moment, it's limited to 1000 experience points max.

**Comment by adamkundrat** [comment]
Added error message. Available in edge.soonaverse.com for testing.
