### ISSUE TITLE
graphical bug in profile display 16 inch screen

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#170]
The boxes are not aligned screen 2560x1600 16 inch 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/77154511/145121938-0c733560-3315-4a67-a2f5-3c8485da3f37.png">

**Comment by frnfa** [comment]
@Phyloiota what browser?

**Comment by frnfa** [comment]
MS EDGE issue, i will lower the priority for now
