### ISSUE TITLE
Inbox - Message Tab for direct relayed messaging within Soonaverse.

### ISSUE THREAD

**Issue by J4DedPrez** [soonlabs/soonaverse-dao#172]
**Is your feature request related to a problem? Please describe.**
I am currently not able to directly communicate with any of the members of the DAO or any other member on the Soonaverse platform.

**Describe the solution you'd like**
To be able to 'Right-Click' on the member, or have a 3dot settings next to member's name to be able to select a 'Message' option.

**Comment by adamkundrat** [comment]
At the moment we assume communication happens outside of the platform. We'll eventually bring discussion forum, notifications and messaging that will eventually allow you to do this. Notifications enhancement - #61
