### ISSUE TITLE
Idea for "pay to join"

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#173]
shonuff and I were joking around about a payment option to enter a space. Mostly this is for closed groups. Attached you'll find the quick brainstorm.
Also to add. Since you are allowing payments to enter, it could be able to vote in a proposal. The reason for it is, nobody would spam if he/she would've to pay to enter.
![Idea_paytouse](https://user-images.githubusercontent.com/65918138/145159284-31552f5b-a0f2-4d1c-9b02-957dc66172c3.PNG)

**Comment by adamkundrat** [comment]
just pin pointing it here. Seems like new Firefly will support messages if so we can enable this even before SC are on main net. It might be time to dust off my iota-button :)

FYI - @shonuffy / @gmanredmond / @centercirclesolutions 
<img width="1263" alt="Screen Shot 2021-12-10 at 8 52 37 AM" src="https://user-images.githubusercontent.com/130610/145611543-0741694d-e472-487a-8679-3fdb768a7743.png">

**Comment by adamkundrat** [comment]
this is on the roadmap and will be implemented in the future
