### ISSUE TITLE
Counting members and spaces total number and graph

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#175]
**Is your feature request related to a problem? Please describe.**
I want to see how many members and spaces have joined already but only see 50+
If I scroll down I will see maybe 100+ and later 150+. But as there are already more than 300 members this takes a long time...

**Describe the solution you'd like**
total amount of members and spaces shown

**Describe alternatives you've considered**
Would be cool to have a graph to see members over time and spaces over time to the the cambrian explosion of DAOs

**Additional context**
![image](https://user-images.githubusercontent.com/45822157/145184752-c7aecb31-054d-492e-8309-1c681717287e.png)

**Comment by adamkundrat** [comment]
Yeah we would like it too but this can be very expensive query especially as we scale. We might need to build counters to do that. We will look into it later in December but for now I'll have to keep this one as low priority.

**Comment by adamkundrat** [comment]
We don't plan to support this as it does not scale. We'll enable API BigQuery possible to get these informations.
