### ISSUE TITLE
I can give the awards to my selfie !!!!!!

### ISSUE THREAD

**Issue by OMJ2021** [soonlabs/soonaverse-dao#177]
**Is your feature request related to a problem? Please describe.**

1 - the creator of the space can give him self as much as he want awards so he can gain Reputation unfairly
      I did this in my space ( Profile : @ welcome-IOTA-2022  ) / spaces : IOTA leader of {{{ Equity & Justice }}} & 
     ( https://soonaverse.com/space/0xfe5ab48258f53a90edb5356a06d8f750fcedf11a/overview )
2 - there is no any notification wen a member joined the space or an award in the space 

**Describe the solution you'd like**
1 - the creator  nor  Guardians of the space  should not  allowed to participate  in  awards  or vote in the same space .
2 - 2 - should  be a sort of mechanism or something that give the award direct without approval from the creator when a member participate at  awards if he or she or they fulfils the conditions of the award. 

thank your patience for my bad English.
![Web capture_8-12-2021_23047_soonaverse com](https://user-images.githubusercontent.com/95631857/145283853-4ab4961e-f578-47ed-8f36-7bcae8d58cc5.jpeg)

**Comment by adamkundrat** [comment]
Hi @OMJ2021 

Thank you for your message. Soonaverse is not here to dictate or tell individual spaces how they want to distribute and give out XP to their members. It's up to each community to be responsible. This means we should not either tell them if guardians can self award themselves ones or twice.

You have to remember XP is not universal across Soonaverse and XP will be valued differently per community. Once Alliances are delivered #157 you would spaces only working with spaces and recognizing their XP when they see fair distribution.

Therefore whilst you can distribute yourself as much XP as you want you will be devaluating your space and more likely have a hard time to form alliances. 

Lastly, all XP will have be backed real token once we go on-chain. Therefore if community is unable to fully back it whatever is not backed will be burned.
