### ISSUE TITLE
Adding more link possibilities for spaces

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#179]
**Is your feature request related to a problem? Please describe.**
I wanted to post a link in my space, but I could only post Twitter, github, or discord links 

**Describe the solution you'd like**
Please add another row where you can post websites and even include a + so that many more pages can be added

**Describe alternatives you've considered**
no

**Additional context**
![image](https://user-images.githubusercontent.com/45822157/145405946-26e2fe49-2140-4579-81fe-3a47d677abc3.png)

**Comment by adamkundrat** [comment]
Thank you! 

We'll provide WYSIWYG editor #147 and you can include links within space description even awards and proposal. I hope this will be delivered end of next week. 

Make sure you subscribe to updates on #147
