### ISSUE TITLE
Improve Error message or Instruction text on XP for Award

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#180]
Currently the limit is 1000XP. Users need to be aware of this or the validation message needs to indicate the limit
This is quick fix until the full changes are implemented

**Comment by adamkundrat** [comment]
Quick fix was just deployed: https://github.com/soonlabs/soonaverse/releases/tag/0.1.1

**Comment by centercirclesolutions** [comment]
Verified in prod
![image](https://user-images.githubusercontent.com/44786846/145453344-4bdffaa4-2ca8-4784-8fab-ac0db23c2ee2.png)
