### ISSUE TITLE
Create and share invite links for spaces/award/member/proposals

### ISSUE THREAD

**Issue by adamkundrat** [soonlabs/soonaverse-dao#181]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/145

<div type='discussions-op-text'>

<sup>Originally posted by **frnfa** December  7, 2021</sup>
how to share your space and invite new members? The best way is to create an invite link like in discord.

by @Rüdiger (https://soonaverse.com/proposal/0x47289b9f9ba578cfedeedbe1fa9f9bf33021c7b3/overview)</div>

**Comment by humaint** [comment]
@Gundavri pls add same share buttons (as we have on NFT detail) everywhere = space/award/proposal detail
![SCR-20220314-ew1](https://user-images.githubusercontent.com/100547127/158084513-28b552f7-5545-4715-8e7d-ce61bc7a22bd.png)

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/branch/nzeg3Gp9KdGpq9WQYtHYWl/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A38740
