### ISSUE TITLE
Support normal domain for discord invites

### ISSUE THREAD

**Issue by antonionardella** [soonlabs/soonaverse-dao#182]
**Is your feature request related to a problem? Please describe.**
I use the discord invite captcha system by IF to add a level of protection to the server invites:
https://github.com/metaversetns/discord-invite-captcha

This system makes it possible to use a normal domain to present a captcha before giving out Discord invites

Normal domains are not supported by Soonlabs spaces
![image](https://user-images.githubusercontent.com/7383572/145487505-ac94cedd-b583-424c-9605-5b5df38711e1.png)

**Describe the solution you'd like**
Support normal domain names for discord invites

Thanks

**Comment by adamkundrat** [comment]
Numerous users raised that its too restrictive. We wanted to avoid ppl entering hazardous URLs but its way to limiting.

We will revisit.
