### ISSUE TITLE
Only the ID and not the name is visible in "Casted Votes"-list

### ISSUE THREAD

**Issue by juppic** [soonlabs/soonaverse-dao#188]
**Describe the bug**
In the list of the casted votes of a proposal, there are three columns: voter, date, option. The "voter"-column only shows the ID (hex-String) of the user and not the username. And the ID is not completely shown since it is too long for the column. So This column doen not really help to identify the user who voted, you will always have to click to get to the profile.

**Expected behavior**
The column "voter" shold show the username (if available), and maybe the avatar as well.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version 94.0.2

**Comment by adamkundrat** [comment]
Thank you for submitting this. We'll try to fix this within this sprint. Meanwhile, I would recommend to use "participants" tab to identify people that have voted.

**Comment by adamkundrat** [comment]
This has been improved and will be release EOW. You can test in edge.soonaverse.com

We've also introduce additional search and filtering options within participants tab.

Thank you for reporting this!
