### ISSUE TITLE
Loading the images takes much too long

### ISSUE THREAD

**Issue by SonOfCrypto** [soonlabs/soonaverse-dao#191]
Your website images are stunning, but from a user perspective, please use thumbnails and not 2592px images.
For a mobile user the loading times are a bug and even on desktop >7mb is way to much for just website images. 

**To Reproduce**
1. open https://soonaverse.com
2. open the network tab
3. reload the page

**Expected behavior**
Images are loading as fast as the wind :)

**Comment by adamkundrat** [comment]
Thank you! We will do it as part of the #112
