### ISSUE TITLE
Notifications dashboard

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#193]
It would be nice if we would have a notification dashboard where one can see, how many people are waiting for a badge or if people actually took part on the proposal. At the current time, we have to manually check, if new members are pending or if they voted. 
Also an option, with a e-mail/app or push(handy) alert for the Guardian would be nice.

**Comment by adamkundrat** [comment]
It's on our backlog, see #61. I hope we will get to this very soon and address this asap. Please make sure to watch issue #61
