### ISSUE TITLE
Clearer indication that a voting has not started

### ISSUE THREAD

**Issue by shonuffy** [soonlabs/soonaverse-dao#197]
Would help with a lot of user confusion to have the field highlighted or to have an indicator that the event hasn't started voting yet.

**Comment by adamkundrat** [comment]
I've improved the message:
<img width="794" alt="Screen Shot 2021-12-15 at 12 38 31 PM" src="https://user-images.githubusercontent.com/130610/146261491-46f076ca-7014-4f4b-9887-9eefef917116.png">

<img width="848" alt="Screen Shot 2021-12-15 at 12 37 43 PM" src="https://user-images.githubusercontent.com/130610/146261489-c69d4461-0f53-471a-bdf3-9c04b4426909.png">
