### ISSUE TITLE
The ability to respond to someone before approving an award

### ISSUE THREAD

**Issue by TangleAccountant** [soonlabs/soonaverse-dao#200]
I just came across a situation where someone submitted a logo via an imgur link to get the Defi Academy logo award. Turns out the link wasn't loading the image. I'd like to respond to this person to let them know I can't approve the award until I get a new link from them. They don't have their Discord name or Twitter handle in their profile, so I have no way of contacting them to let them know.

Additionally, I see this becoming an issue as people will be submitting work for awards, but that work may need some refinement before it's considered complete by the DAO. I think it's reasonable to assume that some work submitted for awards will need some editing done before it can be fully approved and payment sent out. 

I know the Soonaverse isn't a messaging platform, so if messaging isn't possible then maybe guardians could have a "flag" feature that would notify the participant that their submission was reviewed, but needs more work. Maybe the flag could include a small comment option where I could give them my Discord handle so they can follow up.

**Comment by adamkundrat** [comment]
Yes. This something we want to enable in the future. At the moment, when they're submitting the work we tell (within modal) them to make sure to contact you outside of the platform as there isn't any messaging atm.

Once we discussion forum/messaging/notifications this will all be solved.

**Comment by adamkundrat** [comment]
Once discussion forum / messaging this will be solved.
