### ISSUE TITLE
Proposal doesn't create on wen.soonlabs

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#202]
Created a proposal.

filled out all areas, used the vote with badges option for all members, two badges were selected.

it all works fine, hit create proposal and get an "internal error"

![Screen Shot 2021-12-15 at 6 00 33 PM](https://user-images.githubusercontent.com/63729477/146294405-f46d889d-97d2-4d66-81a1-c6beeb315e19.png)
![Screen Shot 2021-12-15 at 6 00 11 PM](https://user-images.githubusercontent.com/63729477/146294436-551d2b8f-394b-4040-9095-a881bcdc3c36.png)
"

**Comment by adamkundrat** [comment]
It's hitting some performance issues with above combinations and it times out. I'll investigate this further. It might be an issue in prod too.
