### ISSUE TITLE
Markdown does not display correctly on discover view

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#203]
**Describe the bug**

Markdown does not display correctly on discover view

## Incorrect
![image](https://user-images.githubusercontent.com/44786846/146298784-5e3d0d29-5145-4a63-b88a-eccba3badfc0.png)

## Correct
![image](https://user-images.githubusercontent.com/44786846/146298808-94f6c1aa-3247-4714-9016-cc0183c06b4b.png)

**Comment by adamkundrat** [comment]
fixed and deployed to edge
