### ISSUE TITLE
In WEN-TEST: (WEN) SoonLabs Welcome Space (WEN) Active proposals

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#209]
Welcome Space(wen) Active proposals

Displays Heading 1 and Heading 2 in bold text (right above member count)

![Screen Shot 2021-12-16 at 10 27 49 AM](https://user-images.githubusercontent.com/63729477/146429154-b256dba2-4d16-4a89-bfcf-24224bd0ec88.png)
.

**Comment by adamkundrat** [comment]
That's correct. It's description I've entered myself:)
