### ISSUE TITLE
Wen- Soonaverse create a proposal doesn't work errors out on signing

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#210]
Wen- Soonaverse create a proposal doesn't work errors out on signing -internal error 

One token one vote, already reported same didn't create using vote with badges.

![Screen Shot 2021-12-16 at 10 44 24 AM](https://user-images.githubusercontent.com/63729477/146430719-800122f9-cfcf-409d-bef1-6d76feef82a4.png)

**Comment by adamkundrat** [comment]
We've increased backend machine.
