### ISSUE TITLE
my overview Active Proposals/Awards

### ISSUE THREAD

**Issue by frnfa** [soonlabs/soonaverse-dao#212]
@adamkundrat ![Screen Shot 2021-12-17 at 9.10.35 am.png](https://images.zenhubusercontent.com/57a5442ce40e5714b16d03f4/d86e80c9-4412-4a22-ba71-762469b696b7)

My Overview - Active Proposals/Awards should show only active proposals/awards not rejected or Completed

**Comment by adamkundrat** [comment]
closing as we will be redoing this.
