### ISSUE TITLE
changing your vote looks like a double vote

### ISSUE THREAD

**Issue by BenRoyce-Society2-com** [soonlabs/soonaverse-dao#213]
![doublevoteCapture](https://user-images.githubusercontent.com/63139512/146591965-0ea8542e-6ce5-4b8f-8bda-80d69dd0ba9e.PNG)

when someone changes their vote, it should be indicated that this what happened. so as not to give the impression that someone is double voting

**Comment by adamkundrat** [comment]
This is no longer enabled to double vote to simplify the process. We might re-enable it again in the future and tweak the UI. Backend still supports it.
