### ISSUE TITLE
Proposal Vote stats need to be more readable

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#214]
**Describe the bug**
At first I thought this said 98% to 188%.  % numbers are a bit small and hard to read

![image](https://user-images.githubusercontent.com/44786846/146625228-a74b635c-d691-4b39-8696-8c55efd77d0e.png)

**Comment by humaint** [comment]
@Gundavri pls update the UI based on latest design

![SCR-20220314-e59](https://user-images.githubusercontent.com/100547127/158083337-5070c2cf-78fb-49ea-adbc-a752b916ec92.png)
![SCR-20220314-e4v](https://user-images.githubusercontent.com/100547127/158083339-9cc954bd-d605-4e21-8293-0da4cb02c7a3.png)

**Comment by humaint** [comment]
- change size of the title
- make the title two line then truncate, collapse in 50% (+ margin between left and right titles)
