### ISSUE TITLE
explain why someone can not vote if they joined the DAO after the vote started

### ISSUE THREAD

**Issue by BenRoyce-Society2-com** [soonlabs/soonaverse-dao#219]
seems to be a common frustration/ point of confusion

for example, see: https://discord.com/channels/397872799483428865/397872799483428867/922154997309911080

**Comment by adamkundrat** [comment]
We've improved the UI for this. We'll implement enhancement (settings that guardian can enable) in the future for proposal to include ppl that join space even after proposal was created.
