### ISSUE TITLE
Improve responsiveness of searches 

### ISSUE THREAD

**Issue by nicole-obrien** [soonlabs/soonaverse-dao#221]
**Is your feature request related to a problem? Please describe.**
When searching for an item using the search bar there is no submission button and I can only submit the search string when I press enter.

**Describe the solution you'd like**
I think if you do not want an enter button, then it would be good to have real time search, and for the search bars to work when the value changes. i.e. every key press you are filtering the results by a more specific criteria. Can help the user find more results as they type, that they might miss if they are too precise.

**Describe alternatives you've considered**
Add enter button.

**Additional context**
Would be nice with this: https://github.com/soonlabs/soonaverse-dao/issues/220

**Comment by adamkundrat** [comment]
We plan to improve this as part of the https://github.com/soonlabs/soonaverse/issues/173
