### ISSUE TITLE
Communication only visible for guardians

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#223]
**Is your feature request related to a problem? Please describe.**
I made an award and said everyone who knows the password gets the award. Now everyone can see the password...

**Describe the solution you'd like**
It would be better if there would also be the possibility to have a private message that only can be seen by the guardinas of the space

**Describe alternatives you've considered**
You should also clearly describe, that everyone can read what you write inside this pop up window where it said: "The whole communication is now handled outside the platform, let the award creator know how to contact you."

**Additional context**
As you can see in the screenshot: Everyone is writing the password to get the reward "Glühwein" and now everyone can claim the award, because it is public available...
![2021-12-22 08_47_35-Soonaverse - Award](https://user-images.githubusercontent.com/45822157/147057433-ce519469-3b24-4e30-8c54-d1d296f5dfa7.png)

**Comment by adamkundrat** [comment]
This is public ledger but we will bring encrypted forums/messaging that will solve this.
