### ISSUE TITLE
Update new search-field

### ISSUE THREAD

**Issue by frnfa** [soonlabs/soonaverse-dao#224]
https://www.figma.com/file/RvjWU0WRjODjDY7Kapy7Bf/Soonaverse?node-id=818%3A7586![Screen Shot 2021-12-25 at 6.31.31 pm.png](https://images.zenhubusercontent.com/57a5442ce40e5714b16d03f4/68d70b4b-0803-4c2c-b55a-a55dc9811d8b)

**Comment by adamkundrat** [comment]
part of https://github.com/soonlabs/soonaverse-dao/issues/220
