### ISSUE TITLE
Bad search field for searching spaces

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#225]
**Describe the bug**

**To Reproduce**
1. Go to '(https://soonaverse.com/discover/spaces)'
2. Click on 'Search field'
3. Type 'Stammtisch'
4. See - No results

**Expected behavior**
The search should find "einfachIOTA Stammtisch" and "IOTA Stammtisch München"

**Additional context**
If I ssearch for "einfach" I find "einfachIOTA Stammtisch", so the search is just very bad...

**Comment by adamkundrat** [comment]
relates #221

**Comment by horaklukas** [comment]
Duplicates #220

**Comment by adamkundrat** [comment]
part of https://github.com/soonlabs/soonaverse-dao/issues/220
