### ISSUE TITLE
Keep clicking on "overview" and "participants" and more and more "Participant" buttons start to appear.

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#250]
Keep clicking on "overview" and "participants" and more and more "Participant" buttons start to appear.

When on the overview of a space and click on Proposals-->Your Proposal-->Overview(of the proposal) two new buttons appear, 2x a "Participants" button.

When is on the overview of a space and clicks on Proposals-->Your Proposal-->Overview(of the proposal) two new buttons appear, 2x a "Participants" !
![multiple prposal butons](https://user-images.githubusercontent.com/63729477/152216588-047feecb-e421-4753-8e6e-2fbc210cfb81.png)

**Comment by adamkundrat** [comment]
btw - this might no longer be an issue in upcoming release so please just re-test.
