### ISSUE TITLE
Unable to set start/end date on proposals

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#254]
https://i.imgur.com/DXH5AYN.png<img width="810" alt="support" src="https://user-images.githubusercontent.com/63729477/152546711-30b118b4-2dc0-4f1c-8c00-d6bfa94b64e7.png">

**Comment by adamkundrat** [comment]
@Gundavri - can you please check / test this with a priority.

**Comment by adamkundrat** [comment]
@gmanredmond - fixed will go live with Alliances issues. It was just visualization issue on proposal page.
