### ISSUE TITLE
Please change "joined DD/MM/YY and time (Soonaverse)" to "Joined Space" and fix ascending/descending order

### ISSUE THREAD

**Issue by Moonshot7161969** [soonlabs/soonaverse-dao#256]
Please change the default order of members who have joined, and also pending members in the Spaces from oldest -> newest
and tweak language/date for it as well.

Suggestion: It should be just "joined space on" (for the respective space) instead of example: "joined 12/6/21, 12:15 AM" which refers to the Soonaverse joined date, and not the spaces joined date.
 
![Shimmer Inu DAO - Pending members list (example)](https://user-images.githubusercontent.com/95666308/152708509-3e908754-f227-44ee-86b3-ba02c35a3991.PNG)

Thanks

**Comment by Moonshot7161969** [comment]
![image](https://user-images.githubusercontent.com/95666308/153101756-5bd47ed7-8f60-4058-86e0-19422aca2944.png)

The order changed again.

The order of pending members seems to be random, not by time stamp.

**Comment by adamkundrat** [comment]
This was now fixed in upcoming release this Friday.
