### ISSUE TITLE
Mobile Version - Award confirmation not available.

### ISSUE THREAD

**Issue by tccflash** [soonlabs/soonaverse-dao#263]
**Describe the bug**
On the Metamask Browser on iOS (maybe it is on Android too, but I can't test it) the buttons to approval the awards is not visible, e.g. not available.

**To Reproduce**
Make an Award and and try to approve this on the mobile metamask browser. 

**Expected behavior**
Button like on the PC viewing website 

**Screenshots**
![52C8478A-8ACE-4961-B559-50BB3835B422](https://user-images.githubusercontent.com/46502426/153910951-4fb02181-8bc8-4849-88e5-fa0c55a3c577.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro max
 - OS: IOS 15.3.1
 - Browser Metamask 
 - Version latest stable

**Comment by humaint** [comment]
@Gundavri can you pls check the logic, there should be the same button available on desktop and mobile
