### ISSUE TITLE
Choosing "Space" when creating a new collection

### ISSUE THREAD

**Issue by callmeworden** [soonlabs/soonaverse-dao#267]
What does the space dropdown mean in the upper right hand corner as shown in my attachement?

![image](https://user-images.githubusercontent.com/78708402/154866839-47f8a7fe-edda-4dbf-8470-c61163f1397b.png)

I was looking to create a collection for the IOTA DeFi Academy, but it wasn't an option in the dropdown.

**Comment by callmeworden** [comment]
Maybe we need an info pop-up box?

**Comment by adamkundrat** [comment]
It only shows spaces with "verified address" as you can only create collection against those. 

Maybe we add info bubble here?

**Comment by callmeworden** [comment]
Ooooh is it because I don't have a verified wallet? That should be in the help text box.

**Comment by adamkundrat** [comment]
Agree. @frnfa
