### ISSUE TITLE
verify Wallet experience / issues

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#268]
**Describe the bug**

Started to verify my Firefly Wallet
Signed to generate new address
got asked to send 1,1190 Mi to the generated address
Did this in Firefly
Received message "invalid Payment"
I tried again, 
Same issue

<img width="537" alt="image" src="https://user-images.githubusercontent.com/77154511/154870072-1996ca4f-d82b-44fd-aa65-b14285b72e32.png">

After refreshing browser and starting the process again it went through
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamkundrat** [comment]
this should be fixed now.
