### ISSUE TITLE
Tooltip for "space type"

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#269]
**Is your feature request related to a problem? Please describe.**
Creating a collection requires to define which "space type" it is for

Needs a tooltip to explain what the different options are

<img width="335" alt="image" src="https://user-images.githubusercontent.com/77154511/154870828-4f24e0f1-9b13-4884-8cf9-449481a7022b.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adamkundrat** [comment]
Help text:

Classic NFTs are the most straightforward in that you upload your images, they’re all visible right away, and people can browse through your collection and purchase what they like. Simply upload and sell!
Generated NFTs add a little mystery into the mix. The buyer won’t know what their NFT looks like until they mint it. The owner of the collection has the ability to put in a placeholder image for the entire collection to give the buyer an idea of what the NFT may look like, but their mint will still be a surprise. This is the most common type of NFT (it’s what IOTABOTs did).
SFTs (Semi-Fungible Tokens) are a hybrid between the two approaches above. The collection creator can create a classic NFT, but they have the option to multiply them. For example, they can upload 10 images, but each image will have a quantity of 100. This is a relatively new term in the space, but a good real world example of this approach would be baseball or football trading cards.
