### ISSUE TITLE
crypric error for to low collection price

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#270]
**Describe the bug**
setting the price for a collection to 2 Mi

generates a quiet cryptic error
<img width="344" alt="image" src="https://user-images.githubusercontent.com/77154511/154871023-89dc6fba-c1d7-4446-a2c0-04704be40f5b.png">
better show "validation error" with an explainer text

Also, add a tooltip or text that min price is 10Mi required
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamkundrat** [comment]
@Gundavri - please make sure validation happens on form and shows the error. Respect export const MIN_IOTA_AMOUNT & constants.
