### ISSUE TITLE
Royality payout must be above 1 Mi

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#274]
**Describe the bug**
I create an NFT with a price of 10Mi 
For the collection, I did set a royalty of 2%

This leads to the error: Royalty payout must be above 1 Mi

I would like to know this already while setting the roality because now I would need to cancel the NFT creation, go back to "edit collection", set a higher royalty, or 
I would need to set the price for the currently created NFT to 50Mi

Suggestion: while setting the royalty for the collection display directly the minimum price possible with this roality
So if someone sets 2% royalty, directly display "The minimum price of an NFT in this collection needs to be 50 Mi because minimum roality payout must be 1Mi"

**Comment by adamkundrat** [comment]
hi @Gundavri 

For now let's add a simply validation to disallow royalty that will be less then 1 Mi (config MIN_AMOUNT_TO_TRANSFER) and show a nice warning on both collection and nft.

We will improve this in the future.

**Comment by adamkundrat** [comment]
please ignore. We'll remove the validation and add warning to user that they have too keep it above 1Mi to get the royalties. If they don't all goes to previous owner.
