### ISSUE TITLE
Wrong display of royalities percentage

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#275]
**Describe the bug**
While setting up a collection, I did input "2" as a percentage of the royalty.

While creating the NFT it accepted this 2% ( I was required to set the price to 50Mi to reach 1 Mi royalty.

Later on, I go to "edit collection and the royalty is displayed as 0,02% instead of 2 %

<img width="476" alt="image" src="https://user-images.githubusercontent.com/77154511/154872662-7e073b82-58a7-40fc-bf51-1b6cda1afdea.png">

Same in the "member discount: my 20% discount is displayed as this: 
<img width="767" alt="image" src="https://user-images.githubusercontent.com/77154511/154872752-f7272531-3fd2-4bd4-b927-0dbb5f79c5de.png">

**Comment by adamkundrat** [comment]
this was fixed
