### ISSUE TITLE
Error while editing collection

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#276]
**Describe the bug**
I changed the royalty of a collection from 2% to 10% 
And I changed so the royalty goes to a different space instead of the initial setted one (my own) 

Saving and signing leads to this error

<img width="328" alt="image" src="https://user-images.githubusercontent.com/77154511/154872908-c5b2e716-7333-412e-8c64-f28dffea263f.png">

**Comment by Phyloiota** [comment]
error is not resolvable. even setting everything back to the initial state and "saving" does lead to that error.

Reloading the browser brings me out of the loop.

When I enter the "edit collection" and have not done any changes, it still requires me to "save" even if I did not change anything. This should not be the case. Only require "saving" if anything got actually edited...

**Comment by Phyloiota** [comment]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/77154511/154874569-0b915436-65e9-4bfd-a85b-a575598b4fd9.png">
https://soonaverse-test--pr247-nft-bijscbfr.web.app/collection/edit;collectionId=0x029bbb05951ba686859d031f95234fb9666427a1

**Comment by adamkundrat** [comment]
this was fixed. Bringing to the top will be solved as part of the #271
