### ISSUE TITLE
Time of NFT release should clearly state what time zone it is in

### ISSUE THREAD

**Issue by shonuffy** [soonlabs/soonaverse-dao#279]
I think its really important for the person creating the NFT to know when their sale is happening. 

![Screen Shot 2022-02-21 at 9 35 37 AM](https://user-images.githubusercontent.com/80289564/155016852-3066f024-4654-4247-98a6-c138eddce9cb.png)

**Comment by adamkundrat** [comment]
Any recommendation here? You want info bubble to explain what the available on means?

**Comment by shonuffy** [comment]
I think something that says. A bubble is fine. 

“All times are reflected in PST timezone"
