### ISSUE TITLE
we should have an example here above these fields so they can understand what they can do in this menu

### ISSUE THREAD

**Issue by shonuffy** [soonlabs/soonaverse-dao#281]
![Screen Shot 2022-02-21 at 9 43 48 AM](https://user-images.githubusercontent.com/80289564/155017667-f23085db-15a6-4ca1-b48f-70719a96c551.png)

**Comment by lazylefteye** [comment]
Yes an example with a clickable "?" would be nice. 
I can't imagine anything under "properties" and "stats" so i'm kinda lost, what those mean
