### ISSUE TITLE
Getting error during NFT set up

### ISSUE THREAD

**Issue by shonuffy** [soonlabs/soonaverse-dao#282]
This is the error message. 
![Screen Shot 2022-02-21 at 10 34 22 AM](https://user-images.githubusercontent.com/80289564/155023497-aef2ad03-9af6-43ce-917d-c2d0de5715cc.png)

These are the settings.
![Screen Shot 2022-02-21 at 10 34 40 AM](https://user-images.githubusercontent.com/80289564/155023593-756d072e-bf5b-4a36-b5d9-44f4bdb4b77d.png)
![Screen Shot 2022-02-21 at 10 34 40 AM](https://user-images.githubusercontent.com/80289564/155023601-99cfb721-7506-4254-8198-25c8dcebaca9.png)
![Screen Shot 2022-02-21 at 10 34 52 AM](https://user-images.githubusercontent.com/80289564/155023615-45089f7c-9149-4534-8e7c-13764731f38a.png)
![Screen Shot 2022-02-21 at 10 35 06 AM](https://user-images.githubusercontent.com/80289564/155023626-9008a09e-ab07-41bb-ba00-41cfbe539491.png)
![Screen Shot 2022-02-21 at 10 35 18 AM](https://user-images.githubusercontent.com/80289564/155023632-50a86808-914c-4d81-90ae-a8371f444657.png)

**Comment by adamkundrat** [comment]
Please append automatically https:// or make it prefix of the input instead.

**Comment by Gundavri** [comment]
After changing REGEXP It makes that field invalid too. 
![image](https://user-images.githubusercontent.com/51381939/155303687-ac21cb11-5bc3-4c62-b7c8-238202034478.png)
