### ISSUE TITLE
Should only show own Collection

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#283]
There is no point in showing other Collections imo (except to see what names are already used) which could confuse people.
If there is only your own collection clickable, it's prob enough. 
![only 1 so no confusion](https://user-images.githubusercontent.com/65918138/155025593-89be387a-213b-4bc1-b316-6aef145c0db5.PNG)

**Comment by adamkundrat** [comment]
very true. Will fix now.
