### ISSUE TITLE
Unclear what I'm setting prices for.

### ISSUE THREAD

**Issue by SeanTMartin** [soonlabs/soonaverse-dao#286]
**Describe the bug**
When creating a collection using 'Classic' mode, the fields of 'Sales Info' is confusing, because the user doesn't know what the fields are for. They plan on pricing their nfts individually, so setting a collection-wide price is confusing.

**To Reproduce**
Create a collection

**Expected behavior**
The user understands all of the fields to fill out.

**Comment by frnfa** [comment]
@adamkundrat can you set this price on a classic nft if populated on a clasic coleection

**Comment by adamkundrat** [comment]
done.
