### ISSUE TITLE
Way to access pending transactions.

### ISSUE THREAD

**Issue by SeanTMartin** [soonlabs/soonaverse-dao#288]
**Is your feature request related to a problem? Please describe.**
If the user fails to complete a transaction, then closes the bubble notifying them of this, there is no way that I can find to review that transaction aside from knowing to refresh the page to get a new notification bubble.

**Describe the solution you'd like**
A tab either on the NFT page or the user's profile that allowed access to the pending transaction.

**Describe alternatives you've considered**
Simply having attempting another transaction put you back into the pending transaction

**Comment by adamkundrat** [comment]
there is pop-up that shows

**Comment by frnfa** [comment]
not fixed but duplicate to #379
