### ISSUE TITLE
NFT Marketplace - error format for price level condition

### ISSUE THREAD

**Issue by NewBuidler** [soonlabs/soonaverse-dao#291]
When creating a new collection,

using a price <  10 

There is the following error format in the pop-up  window:

```
Validation failed: [{"message":"\"price\" must be greater than or equal to 10000000","path":["price"],"type":"number.min","context":{"limit":10000000,"value":1000000,"label":"price","key":"price"}}]
```

Maybe the error message should be formatted for the average user.

**Comment by adamkundrat** [comment]
This will be fixed as part of the #270
