### ISSUE TITLE
NFT collection Filter doesn't work

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#293]
The NFT collection filter on my profile doesn't work, it keep showing me the NFTs I have when I select a specific collection

![image](https://user-images.githubusercontent.com/100204340/155127856-f346fafc-0ffd-4ff3-ab7f-3b92e080eb5e.png)

![image](https://user-images.githubusercontent.com/100204340/155127899-7687d42a-8c56-4749-b85a-2583d25651b8.png)

**Comment by adamkundrat** [comment]
🙄 i'll think this was forgotten little bit. We will fix.
