### ISSUE TITLE
NFT editing option 

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#294]
I've created a collection, and then some NFTs inside it.

Before approving the collection, it would be nice to have an option to edit NFTs info, currently it is not possible.

**Comment by adamkundrat** [comment]
There is an option to edit on collection? You don’t see the edit button?

**Comment by adamkundrat** [comment]
This is done on purpose as it'll be eventually locked on chain. You have to make sure you use the preview function. 

We might eventually support it before collection is approved but right now we simplified it for us little bit.
