### ISSUE TITLE
Collection shown in the Marketplace before approval

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#295]
I've created a collection, which I could see in the marketplace even before approving it.

![10](https://user-images.githubusercontent.com/100204340/155139193-a5557e51-3362-4653-a155-f84276f35f15.JPG)

![11](https://user-images.githubusercontent.com/100204340/155139202-923a911a-b2b1-43f5-b908-4ee7a9d8788b.JPG)

**Comment by adamkundrat** [comment]
fixed, it'll be available in next 30 min.
