### ISSUE TITLE
Available NFT not showing 

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#296]
When I check my collection (or any other), when there's an available NFT it is only shown in the 'ALL' tab but not in the 'AVAILABLE' tab.

![21](https://user-images.githubusercontent.com/100204340/155140193-c734d873-59ac-45ec-b6da-07473f711bcb.JPG)

![22](https://user-images.githubusercontent.com/100204340/155140195-39619f6f-9d59-47c5-a23c-9865cee8c44d.JPG)

![23](https://user-images.githubusercontent.com/100204340/155140196-f6b11de0-c2ee-4f13-8369-c24e6cefbdc2.JPG)

**Comment by adamkundrat** [comment]
What collection is this one?

**Comment by sexypotato-wagmi** [comment]
My own, it's call "sexypotato OG collection"

**Comment by adamkundrat** [comment]
fixed, will be available in next 30 min.
