### ISSUE TITLE
Guardian with different permissions

### ISSUE THREAD

**Issue by Peratron** [soonlabs/soonaverse-dao#297]
In the future I would like to have a guardian who can confirm everything quickly, without ledger.  However, this guardian should not be able to delete other guardians. It should be possible to quickly confirm simple things without using the ledger every time. But safety should not suffer as a result. You should be able to severely restrict this access without a ledger. Is this possible in the future?

**Comment by adamkundrat** [comment]
Great idea! We plan to introduce moderator role with our discussion forum which will support this.
