### ISSUE TITLE
Filter by space doesn't work for Available and Owned NFT

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#298]
From the marketplace, if I select my own space I can see my collection. BUT is I select to see 'availables' or 'owned', it brings back all (available or owned) NFTs from all collections.

![30](https://user-images.githubusercontent.com/100204340/155145223-17028d4c-0d86-42ec-8c13-b9fdbbfbdbee.JPG)

![31](https://user-images.githubusercontent.com/100204340/155145226-a6629286-3b54-4040-978c-2fbecc836d21.JPG)

![32](https://user-images.githubusercontent.com/100204340/155145229-8bf34018-7a5d-42b3-ad3a-1fdfa72d4d4e.JPG)

**Comment by adamkundrat** [comment]
yes. we don't support such search yet.

I'll keep this open and we might improve this in the future.

**Comment by adamkundrat** [comment]
Hi @sexypotato-wagmi 

We don't allow to combined filter options at the moment. We'll eventually support it but it gets rather complex for us to do it right the way.
