### ISSUE TITLE
Logging with different wallets.

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonlabs/soonaverse-dao#300]
Currently it's not possible to login with multiple accounts (in different moments), once you sign the contracts with one address, you cannot change it in the Soonaverse even though changing it on Metamask.

Before the release of the public alpha version, it was possible on the testing.

**Comment by adamkundrat** [comment]
This works for me. Can you please expand on this and provide steps to reproduce? I can't replicate this.

**Comment by sexypotato-wagmi** [comment]
Hey Adam, it works now.. I don't know why I couldn't change accounts before!

**Comment by adamkundrat** [comment]
Yeah weird…. We need #207 asap and it will eliminate most of these weird issues
