### ISSUE TITLE
NFT collection minting should-not require any tech knowledge for NFT creator. Utility needed like https://www.launchmynft.io/

### ISSUE THREAD

**Issue by gablucoin** [soonlabs/soonaverse-dao#302]
https://www.launchmynft.io/

Minting a collection should be as super easy as supported in above website.Does soonaverse provide such utility?
 As AN ARTIST/PAINTER I have no intention to go through hashlib or any other lib and become a developer.
If soonaverse doesnot support such utility it  will not have any useful differentiator from other marketplaces.
 See Creators r of two type--1)Real Creators 2)Creators with dev contact..So we will be missing out real creators here..
The basic  problem with Dev is developer mindset with which features are devloped.
 Critical thinking should be done for the EndUser Customer Ease of accomplishing a workflow. 
Here the NFT creator is an artist/designer or painter who doesnot process the tech knowledge hashlib lib ,nodejs.
 The quality suffers because the NFT artsist in other marketplace are mostly non artist rather developer minting their collection left and right and the actual Artists are left behind.

**Comment by adamkundrat** [comment]
I hope we meet that requirement with our release
