### ISSUE TITLE
image is not displayed in NFT

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#304]
**Describe the bug**
created an NFT in an existing collection, uploaded a Banner in the collection

created an NFT - uploaded an image, this image is not displayed in the NFT

<img width="317" alt="image" src="https://user-images.githubusercontent.com/77154511/155323349-59859d45-58d3-4156-b5c2-39a59cc00471.png">
https://wen.soonaverse.com/collection/0x029bbb05951ba686859d031f95234fb9666427a1

Both upload fields for banner and image would allow me to upload multiple image

**Comment by adamkundrat** [comment]
@gundavri

I thought we have already fixed this issue and make the image mandatory. Please can you check how is this possible? Is image mandatory on NFT as well as banner on collection?

**Comment by adamkundrat** [comment]
@phyloiota - this is generated NFT/SFT. Did you upload the placeholder on the collection?

When it’s generated NFT/SFT you will not see the images after upload. You will only see them once they’re minted.
