### ISSUE TITLE
[FEATURE REQUEST] Sort pending users of awards by participation entry time

### ISSUE THREAD

**Issue by boxcee** [soonlabs/soonaverse-dao#307]
**Is your feature request related to a problem? Please describe.**
Following the latest airdrop of Shimmer Sheep, it seems pending members of an award are not sorted by any means. At least the guardian reported that the order of the list kept changing whenever he accepted a new participant. As a result, some early members didn't get a spot.

**Describe the solution you'd like**
1. Sort pending users by participation entry time by default.
2. Add an option to accept participants randomly. I don't know how the UI looks like, but I am thinking of a button next to the accept button, which accepts participants randomly out of the pending participants. This way the guardian can chose how they like to do it.
3. The entry shows the time a member joined the space. Maybe add the time they participated in the award/proposal/badge. This way there is no later guessing of who should be in and who shouldn't.

**Additional context**
Talking about this here: https://twitter.com/pxdg3/status/1496502008601272321

**Comment by adamkundrat** [comment]
This has been now improved. We will now show when they've participated on. We might improve this further in the future.

Thank you for the suggestions.
