### ISSUE TITLE
Pending Verification Step is continuing - Transaction was already approved

### ISSUE THREAD

**Issue by DoktorTangle** [soonlabs/soonaverse-dao#308]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

I waited for 15 minutes and I did not got to the final step. I closed the overlay and the page shows me know - your address is verified

![Screenshot 2022-02-23 192314](https://user-images.githubusercontent.com/86572338/155383027-5d76c617-c347-4b9c-9401-c79ae599d7bf.jpeg)

**Comment by adamkundrat** [comment]
Did you get your funds back? could you provide tangle reference for your payment pls?

**Comment by tccflash** [comment]
I had the same issue on the test.soonaverse.com site today evening (CET). The founds would not be refunded, but the wallet status is verified.

**Comment by adamkundrat** [comment]
this was fixed. I just corrected our test account... 
you should all get refunded pending balances....whenever it was a refund or royalty/previous owner payment.

We had refreshed our keys last night and I forgot to update test accounts....
