### ISSUE TITLE
General Filter and UI Improvements to Discover Page

### ISSUE THREAD

**Issue by jpeeling13** [soonlabs/soonaverse-dao#309]
Hey There! I'd like to request 2 general enhancements to the Discover Page that would make finding Daos easier:

**1.) Add new filter options on the Discover page so that I can see just the Dao spaces I've already joined, or only new Daos that I haven't joined yet:**
<img width="800" alt="Screen Shot 2022-02-24 at 9 00 37 AM" src="https://user-images.githubusercontent.com/9746778/155549647-7374595a-0f49-4f4c-8f51-936337d7eba5.png">

**2.) Add an icon/field to the Dao space "cards" so that I can visually tell that I'm already a member of the space:**

<img width="300" alt="Screen Shot 2022-02-24 at 8 55 19 AM" src="https://user-images.githubusercontent.com/9746778/155548967-0d9176db-f554-4753-8653-128192860cc9.png">

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/branch/nzeg3Gp9KdGpq9WQYtHYWl/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A34431

@Gundavri can you pls add joined badge as in design

**Comment by humaint** [comment]
@adamkundrat are we able to show that badge when all spaces displayed?

**Comment by Gundavri** [comment]
@humaint Figma link not working

**Comment by humaint** [comment]
it seems this works only for one of the spaces in the list but not the rest, see screens, Im part of both spaces shown, but just one has the lable joined

![SCR-20220327-dyj.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/f8609a09-a18e-44f5-842e-6e7f3d314351)![SCR-20220327-dyt.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ea79cbf5-7c46-4c1a-80c0-90c33a70bbd1)

**Comment by adamkundrat** [comment]
This is due you not having any XP. This will require protocol fix.

**Comment by adamunchained** [comment]
part of https://github.com/soonlabs/soonaverse/issues/688
