### ISSUE TITLE
Pending-members queue disappear 

### ISSUE THREAD

**Issue by mbarrueto** [soonlabs/soonaverse-dao#310]
After changing the 'Space Type' from 'Requires a member approval' to 'Open to anyone to join instantly', and PRIOR to approving pending members, the queue (4 members list) disappear, leaving me wondering about the member-status of these 4 members.

See pic attached for ref. reading '1 members (4 pending)'

Space name: [Piratas Peruanos](https://soonaverse.com/space/0x38c5046844d9e2daa577663622c3a64982b444ad/overview) 

![image](https://user-images.githubusercontent.com/24359082/155564310-227cb21c-b6a1-4d2e-9aa3-e135611d9483.png)

**Comment by adamkundrat** [comment]
Thanks for reporting. Fix will be released for this tomorrow.

**Comment by mbarrueto** [comment]
Thanks much Adam!
