### ISSUE TITLE
Required Badge for create NFT Collection won´t work

### ISSUE THREAD

**Issue by tccflash** [soonlabs/soonaverse-dao#311]
**Describe the bug**
If I set everything correct and would like to choose a specific award on the last tap of the collection creation site, named "Required Badge" this won´t work for me. I created a Badge, took it by myself and tried to set it up for a buying action. But the award isn´t shown theire, as not as i can write it in handly. Than it´s still away after clicking outside the field.

<img width="458" alt="Bildschirmfoto 2022-02-24 um 20 14 44" src="https://user-images.githubusercontent.com/46502426/155591721-33d8ed89-1f58-47fd-92a7-a285b3b5dd96.png">

IMac with Chrome
Iphone with Metamask Browser

Both the same.

**Comment by adamkundrat** [comment]
This has been fixed.
