### ISSUE TITLE
Incorrect word / line breaks in the marketplace displays

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#316]
**Describe the bug**
Words in frames are not correctly divided once a row is finished

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/77154511/155828639-5df93ecb-786f-4c0c-9378-b720e5e45d2f.png">

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/77154511/155828658-15aaf723-2a7c-4688-b615-2ac24524da2a.png">

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/77154511/155828678-167f6dca-16e8-4206-94ce-f0b77b7a4ca6.png">

Browser is MS Edge

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by humaint** [comment]
@Gundavri pls make sure you have "word-break: break-word;" when .line-clamp-3 is used

and don't use .break-all for titles
