### ISSUE TITLE
Setable quantity per NFT

### ISSUE THREAD

**Issue by tccflash** [soonlabs/soonaverse-dao#318]
I think it would really nice, If we can set up, that a specific NFT can only be sold one time per member/badgeholder. I think that would do everything more fair for sales or something like that.

Second cool thing would be, if we can make directly sends NFTS as like this one on opensea.But I think that could be a problem with the dust protection.

**Comment by adamkundrat** [comment]
Yes we plan to implement this as part of https://github.com/soonlabs/soonaverse/issues/437

We'll introduce one purchase per member on the Collection. 

We will introduce ability to send NFTs to someone else but it'll require 1Mi so it can be recorded on tangle.
