### ISSUE TITLE
IOTA fund not returned when verifying Space's Wallet Address

### ISSUE THREAD

**Issue by Tombaaa** [soonlabs/soonaverse-dao#324]
Wanted to add my IOTA address to my Space. Worked like confirming the address for the profile.
However, the funds were not returned. See screenshots of unreturned IOTA's

This is the message ID
857825b1d96b073ca4569e509008f97e34d9521b9a5d1f4d6bf4a17801868273

And this the receiving address:
iota1qp65xjhd89urapuw2pufwt4alpyc78hhjhs28cwsrpexmu2a4qr0jx78lz8

![image](https://user-images.githubusercontent.com/77152394/155877658-8708eb13-003a-4971-bd28-643a03858968.png)

The wallet for the Space was verifiyed, however, the funds sent not returned (yet, after more then 1.5 hours)
![image](https://user-images.githubusercontent.com/77152394/155877691-497d2b92-9f93-45cc-9397-b630381bb4f5.png)

**Comment by adamkundrat** [comment]
Hi @Tombaaa 

Thank you for reporting this issue. I can see your transaction here: https://explorer.iota.org/mainnet/message/857825b1d96b073ca4569e509008f97e34d9521b9a5d1f4d6bf4a17801868273

It seems refund was processed with 15 minute delay unfortunately. We're trying to improve our process of detecting unhealthy hornet IOTA nodes to make sure this delay can be reduced. We'll get there.

**See refund here:** https://explorer.iota.org/mainnet/message/0666acbbf171cbe9697c18cfde161388427b25062cf520d233f136155194c5ef

**Comment by Tombaaa** [comment]
Dear Adam, finally I can see the transaction in my firefly wallet, thank you very much.
