### ISSUE TITLE
Can't unselect Space to get Royalties

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#326]
**Describe the bug**
If you accidentally select a space to get royalties then decide not to there is no way to clear it. Even if you unselect the checkbox to assign royalties to another space it still assigns royalties to the previously selected space

### This is a pretty critical issue

**Comment by adamkundrat** [comment]
Hup. Will fix.

You can actually just set the collections’ space. This is what happens in the background.

**Comment by adamkundrat** [comment]
When user unselect checkbox. Royalty should be set back to main space of the collection.

**Comment by adamkundrat** [comment]
fixed
