### ISSUE TITLE
Unable to initialize, connect, or open MetaMask

### ISSUE THREAD

**Issue by maxwellmattryan** [soonlabs/soonaverse-dao#327]
**Describe the bug**
When trying to initialize, connect, or just open MetaMask for an action (signing, sending, etc.) it will NOT open. I noticed that having the Rabby chrome extension installed is what is causing this behavior, but I am not sure why.

**To Reproduce**
1. Install Rabby defi wallet (see [here](https://chrome.google.com/webstore/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch), is a wallet extension recommended by [Debank](https://debank.com))
2. Go to [Soonaverse](https://soonaverse.com) and click on "Connect"
3. Should notice two error notifications: "Failed to initialize MetaMask, try reloading the page again." and "You must unlock your MetaMask first!" (despite having tried / done both of those things)

**Expected behavior**
I should be able to sign in to Soonaverse if I have the MetaMask extension, regardless of other extensions. (I did notice that this was a problem on Debank and Spookyswap too... :thinking:)

**Screenshots**
![Screenshot from 2022-02-28 08-07-30](https://user-images.githubusercontent.com/44885822/155997174-aaefb176-3266-4fca-aa2d-4d7e645180ba.png)

There's were no logs in the console corresponding to this issue.

**Desktop (please complete the following information):**
 - OS: Ubuntu / MacOS / Windows 10
 - Browser: Chrome
 - Version: 98.0.4758.102

**Comment by adamkundrat** [comment]
This happen due "Rabby defi wallet extension" right?

**Comment by maxwellmattryan** [comment]
> This happen due "Rabby defi wallet extension" right?

Yes, it seems that way. Whether or not it is a specific problem with my Chrome version or something I'm not sure. Uninstalling it caused everything to work immediately as it usually does :+1:

**Comment by adamkundrat** [comment]
I see. Glad you got it fixed. We'll introduce #207 soon and it should eliminate these issues.
