### ISSUE TITLE
If you use smaller browser windows, a bug apears

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#331]
If you scale 2 browser windows on your screen (see picture) you're not able to upload anything or work on it. The UI is bugged.

Why did I found this bug?
I tried to watch "Soonaverse NFT Tutorial - Add Multiple NFT's to a Collection" on the left browser window and working on the right browser window.

Windows 10 - Browser: Google Chrome "left" / Mozilla Firefox "right"
![Issue_window_scale](https://user-images.githubusercontent.com/65918138/156201232-ac7b2740-df70-4bd3-9fa2-1f168d4919e4.PNG)

**Comment by humaint** [comment]
this happens when you resize the window from desktop to mobile breakpoint. not sure what's the best solution to fix this? should we force the page refresh?

**Comment by Gundavri** [comment]
Fixed it without refresh

**Comment by adamkundrat** [comment]
@Gundavri - can you please explain? did you add a fix for it or are saying they should refresh ( I don't think that's acceptable) ?

**Comment by adamkundrat** [comment]
oh I see the fix now, ignore above.
