### ISSUE TITLE
no refund after failed wallet verification

### ISSUE THREAD

**Issue by blacksaff** [soonlabs/soonaverse-dao#332]
In my first attempt to get verified, I took a little too much time. I initiated the tranfer of 1.3864 Mi before the time was over but the payment went through after the time elapsed. The verification process failed and I did not get my Mi back. Is there a way to be refunded ? thanks

Send address : iota1qqmdwxl7ls96fv6m0ty05s3vc9hhfzyxhpl8kaq09ny2qxzpw56uguckr8g
receive address : iota1qrdm9u9pvx2lgel4jejmm02w8xep5ptj7nrspk0qgpfq025eayxz5fpc74u
amount : 1.3864 Mi
soonaverse profile : Blacksad

If possible, I think that allowing for a little more time would be helpful.

**Comment by adamkundrat** [comment]
this has been corrected yesterday. Let us know if not. Thank you for reporting this issue.
