### ISSUE TITLE
Sorting Properties of NFTs in different order

### ISSUE THREAD

**Issue by vromvonbeyond** [soonlabs/soonaverse-dao#333]
**Is your feature request related to a problem? Please describe.**
I bought a lot of Soonaverse NFTs and I wanted to find out if I have an Ultra NF3. So I was missing a feature to easily export a .csv file of all the properties. I needet to copy/paste all properties and manually sort it in Excel. That's where I found out, that the ordering of the properties had been different for every NFT I opened. So it was even more complex to sort them all together in one excel file

**Describe the solution you'd like**
First of all, the 4 most important properties should always be on top and maybe even marked in bold letters. Then it would be nice if the ordering of the properties would be the same, so for example: 1. Water = .. 2. Planet =.. 3. Background =.. 4. Fauna = ...  and so on And not like it is today in next NFT it could start with 1.Fauna, 2. Background and so on.
And then I would propose it would be nice to just download a .csv file of all properties of one or even of all NFTs someone has

**Describe alternatives you've considered**

**Additional context**
Here are two pictures of properties from 2 different Soonanauts.
The ordering of the properties is different

![image](https://user-images.githubusercontent.com/45822157/156333535-ed482632-b96e-4cf3-9af4-28a59c3914c8.png)

![image](https://user-images.githubusercontent.com/45822157/156333642-2eaef473-e7cb-4af9-8bbb-0ac3ab0a8cb9.png)

**Comment by Howcool6** [comment]
Ja ist mir auch aufgefallen. Kannst du nich was erstellen wo jeder seine NFT Eigenschaften eintragen kann, um diejenigen zusammen zu führen, die passende NFTs haben ?

**Comment by csxiong** [comment]
No need to bother, check the ID, the same ID is the same for all 4 attributes. This has already been verified.

**Comment by adamkundrat** [comment]
We should still make sure it's at least ordered alphabetically. Will fix.

**Comment by adamkundrat** [comment]
We've tweaked the system to make sure it's ordered alphabetically at least. It's coming into prod soon.
