### ISSUE TITLE
Invalid discount calculation for NFT collection

### ISSUE THREAD

**Issue by ivanbeerlama** [soonlabs/soonaverse-dao#337]
**Describe the bug**

Discount not computed properly for collection (Iota Whales). The 30% price is shown instead of the 100% price discount while holding 50XP.

**To Reproduce**
1. Go to https://soonaverse.com/space/0x87594007c6ecf43a1c85e1f35be99d5729c8608f/collections
2. Hold 50XP

**Expected behavior**
Price should show as 0MI. If multiple discounts are active, pick the highest one. 

**Screenshots**

![image](https://user-images.githubusercontent.com/99087735/156648992-323b63ef-9f10-4b13-9067-5e7d68cb3e2c.png)
![image](https://user-images.githubusercontent.com/99087735/156649005-127d9f33-f623-475f-bc9a-93a4cfeadba4.png)

**Desktop (please complete the following information):**
 - OS: osX
 - Browser: Chrome

**Additional context**

**Comment by adamkundrat** [comment]
Ah this seems to happen due ordering. We’ll fix that.

**Comment by adamkundrat** [comment]
This has been now corrected and fix is coming to production within next 1h.

Thank you for reporting this.
