### ISSUE TITLE
Collection placeholder image disappears when editing collection

### ISSUE THREAD

**Issue by pxdg2** [soonlabs/soonaverse-dao#379]
**Describe the bug**
When editing a collection, the placeholder image gets lost and replaced by the banner image.

**To Reproduce**
- click on edit collection
- edit anything
- save
- placeholder image is now the same as banner image

**Expected behavior**
Still display the previously uploaded placeholder image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X Monterey
 - Browser: Firefox

**Additional context**

**Comment by andyfront0** [comment]
Having the same problem. Placeholder image does not save after edit and neither does website link.
