### ISSUE TITLE
Can't see full submission of an award

### ISSUE THREAD

**Issue by callmeworden** [soonlabs/soonaverse-dao#38]
**Describe the bug**
When you go to the Participants tab of an active award, you see people who have applied for the award. You can see the beginning of their submission, so you'd assume that when you click on it, you'd be able to view their full submission, but instead it takes you to their profile. You can never see someone's full submission unless you're a Guardian. I think we should either remove the beginning of the award application text or take you to the full award application if you click on it:

![image](https://user-images.githubusercontent.com/78708402/144136000-49fae8dc-4609-4d22-b4c9-70b2de1c17ab.png)

**Comment by callmeworden** [comment]
I have people submitting real requests to earn awards in the DeFi Academy space. Since I can't read the full submission, I'm having trouble rewarding the correct participants. Can you guys find the data for me on the backend until the UI is fixed?

**Comment by adamkundrat** [comment]
let me put tooltip there at least.

**Comment by callmeworden** [comment]
In the edge environment:

There's no way to copy and paste the text in the award. If you go to drag across the text to copy it, it just picks it up as a link instead of a string of text.

**Comment by adamkundrat** [comment]
More improvements on this will come in this release and it should fix above. ill let you know once you can test.
