### ISSUE TITLE
User was issued OG badge but cannot access collections

### ISSUE THREAD

**Issue by shonuffy** [soonlabs/soonaverse-dao#382]
I asked him to send me a screenshot of his account. He clearly shows the OG badge. However, when I go to his public page I cannot see his badges. 

![image](https://user-images.githubusercontent.com/80289564/156938553-988c445a-e8dd-4f34-9be3-e0cfe213328d.png)

![Screen Shot 2022-03-06 at 9 14 37 AM](https://user-images.githubusercontent.com/80289564/156938578-da1c5416-2b22-40f3-a0d0-22d1912cce84.png)

**Comment by shonuffy** [comment]
![image](https://user-images.githubusercontent.com/80289564/156944228-2cbcf6d3-6846-4c62-87e3-e0d7a8bea737.png)

He can see the collection button but it doesn't work

**Comment by adamkundrat** [comment]
Will investigate in few hours and let you know.

**Comment by adamkundrat** [comment]
Are you sure this is still an issue? I can see he created a collection: http://www.soonaverse.com/collection/0x34f75bfe9fbf0c45a8b3d63265931065a94cd32e

**Comment by adamkundrat** [comment]
feel free to re-open if this is still an issue

**Comment by shonuffy** [comment]
Yeah, just got back and it seems this was resolved. Thank you.
