### ISSUE TITLE
Display 'Sale Starts' date on the front page of the collection

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#385]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/371

<div type='discussions-op-text'>

<sup>Originally posted by **ZiiZouu** March  5, 2022</sup>
Right now you only see the 'Sale Starts' date after klicking on the collection and then going one level deeper by klicking on the 'Buy now' field...

In my opinion having the 'Launch date' or 'Sale starts' info directly on the main page of the collection maybe next to the creator and the creation date, etc. would be a nice feature.</div>

**Comment by humaint** [comment]
I have some design updates pending associated with this issue

**Comment by adamkundrat** [comment]
yeah I think we need to clean this up it's certainly creating confusion.

**Comment by humaint** [comment]
working on desing

**Comment by humaint** [comment]
@Gundavri there are some updates on collection detail regarding the start time

-- show starts in box according to design  (maybe there is the same issue reported alredy) https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2933%3A30836

-- collection card tag https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2984%3A30943

-- NFT card tag https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2984%3A30943

**Comment by adamkundrat** [comment]
@humaint - try to post the screenshot here sometimes when you click those Figma links it does not take you to specific page:(

**Comment by humaint** [comment]
pls @Gundavri implement also a logic which shows different titles when auction/sale

- Sale starts / Sale ends
- Auction starts / Auction ends 

not on cards just NFT detail

**Comment by adamkundrat** [comment]
@Gundavri - all the logic and functions are there for this. I’ll be online early in the morning tomorrow if need to chat.
