### ISSUE TITLE
invalid - use discussion forum

### ISSUE THREAD

**Issue by simonmat95** [soonlabs/soonaverse-dao#392]
I have a few suggestions regarding the NF3 .....

1. Please introduce detail filters which showcases all the attributes so that we can find exactly the nft we are looking for 

2. When launching the marketplace....normally there would be a buy now and a place bid option
.....please include a option where people can exchange an nft in place of another one ....the outcome is that the ultra nf3 can be acheived in that way( both nft should be locked during the moment of exchange )

3. Most projects arent searchable by name (eg: iotapunks ...all are named like that so if i want to search a specific punk ....i have to scroll and find ), please make mandatory for new projects to include the distinct number in their name itself

**Comment by adamkundrat** [comment]
1. This is outside of scope of Soonaverse. Each NFT can have different attributes so it'll be impossible for us to consolidate. We'll release an API in near future and ppl can build purposely build pages (with search) for their collection.

2. this is coming.

3. Our search is currently limited. This will be improved. See https://github.com/soonlabs/soonaverse-dao/issues/220
