### ISSUE TITLE
Edit collection show Everyone but collection is Space only in system and Info screens

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#405]
**Describe the bug**
Entering a collection and the Type was set to Space members only. The edit screen shows Everyone which is not correct. There also could be an issue that allows the collection to be saved as Space only but shows Everyone.

![image](https://user-images.githubusercontent.com/44786846/157563698-b175603d-85e1-4ea5-8480-508a415d8a46.png)
![image](https://user-images.githubusercontent.com/44786846/157563875-539a3c87-5528-40f8-b4b6-5627c10f84d4.png)

**Comment by adamkundrat** [comment]
@Gundavri - it seems value is not correctly set on edit please fix
