### ISSUE TITLE
User shows sale in progress for over 10 min

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#408]
**Describe the bug**

User tried to buy NFT but got the message another sale was in progress. Even 10 minutes later. Reloaded browser and Logged out and back into MM and that resolved the issue.

![image](https://user-images.githubusercontent.com/44786846/157734417-532454d1-aa30-46cb-a9a9-3090764d8083.png)

**Comment by adamkundrat** [comment]
This should be fixed. It was due delay.
