### ISSUE TITLE
Main frame and sidebar lower border are not aligned in Profile

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#41]
empty space on the bottom...
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/77154511/144143348-6aad603e-5f75-4e86-a0da-eadcce05f022.png">

**Comment by frnfa** [comment]
pls

**Comment by adamkundrat** [comment]
added "height$ | async" in layout.component.html, see comment at the top.

**Comment by adamkundrat** [comment]
finally got this working!
