### ISSUE TITLE
Description says IOTA logo, but presents wrong NFT image in this case an Assembly Logo

### ISSUE THREAD

**Issue by gmanredmond** [soonlabs/soonaverse-dao#412]
Description says IOTA logo, but NFT shots Assemble Logo.[
](https://discord.com/channels/892481940953915433/941859625047822386/951301039783555082
[6:46 PM]
You can see the NFT here: 
https://soonaverse.com/nft/0x115a620d1bc2aecd26270c5de5db7f3cf06f3c39 (edited)

https://discord.com/channels/892481940953915433/941859625047822386/951301039783555082
)

more on same:

 two of my friends in soonaverse are running into the same issue with regards to FireFly NFT Collection Sale.
DashParrIzaya 
https://soonaverse.com/nft/0x1c84d635cbcd759b40026dce1259fa2e3477b77c

HelgaPataki
https://soonaverse.com/nft/0x115a620d1bc2aecd26270c5de5db7f3cf06f3c39
Both have same description:
"Black and white blackhole Cosmo GM with Iota logo"
Both NFT Show the incorrect Logo. 
Plz lmk if you need more details or information, ill wake em up if needed. (edited)

![image](https://user-images.githubusercontent.com/63729477/157751768-08c05fe3-c5dc-4812-a098-33dbc98a6454.png)

**Comment by adamkundrat** [comment]
@gmanredmond - this not a bug. The author have uploaded twice the same NFT. He must have not noticed a duplicate in his CSV. They should raise this with the artist.

We can eventually have some file duplication validation in place. If you think it’s worth it, feel free to create an idea for this in discussions.
