### ISSUE TITLE
cant participate in an award

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#42]
from the discover page i found the durian challenge, I could click on "participate" and wanted to submit my participation.
Clicking on the button to submit brings an error that I am not yet member of the space and cant participate.

You should hide or grey out the button for non-members.

Also I don't see where I could become o member on this page...

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/77154511/144143955-44395985-d26a-4261-9564-e4f8b622b138.png">

**Comment by adamkundrat** [comment]
Button disabled and message tweaked. Will be released next week. Available in edge.soonaverse.com for testing.
