### ISSUE TITLE
MP4 Placeholder don't support Autoplay now.

### ISSUE THREAD

**Issue by tccflash** [soonlabs/soonaverse-dao#438]
If you set a MP4 for the placeholder function, this one shows the play Button only. So a user have to click on play to see the placeholder. Think that's not what you would like. 😄

**To Reproduce**
Steps to reproduce the behavior on wen.soonaverse.com:
1. Go to 'SFT Test Collection'
2. Scroll down to 'available collection'
3. Click on the play Button on the placeholder
4. See error what happens. 

![image](https://user-images.githubusercontent.com/46502426/158011727-24d7967f-be37-48c9-824e-cc55eac57f8b.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamkundrat** [comment]
Autoplay is disabled on purpose. This would slow down browsing experience in the kist big time. We will most likely only have it enabled on individual NFT page.

I'll look how we can tweak clickthrough the nft-card

**Comment by tccflash** [comment]
Ah okay. Make sense. But than it looks better with a normal jpeg I think.

**Comment by adamkundrat** [comment]
This has been tweaked to show first frame of the video.
