### ISSUE TITLE
Member must hold at least one NFT from each selected collection.

### ISSUE THREAD

**Issue by adamkundrat** [soonlabs/soonaverse-dao#441]
We now support "Member must hold at least one NFT from each selected collection.". 

We have the option but we don't visualize this information under the collection. It should be similar to how we show badges if collection is restricted to member's with certain badges.

![Screen Shot 2022-03-12 at 2.48.33 PM.png](https://images.zenhubusercontent.com/54f851af4f7a08fbb7f242c5/02eca0c6-fb07-41d3-ba40-1724f4d5027a)

**Comment by humaint** [comment]
working on design

**Comment by humaint** [comment]
@Gundavri design ready https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3025%3A31560

![SCR-20220327-d7m.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ebf05a49-b109-4ef2-8785-9be75542664e)
