### ISSUE TITLE
Unable to find IOTAnauts in discovery search

### ISSUE THREAD

**Issue by IOTAnauts** [soonlabs/soonaverse-dao#447]
**Describe the bug**
Searching for title of my Soonaverse space does not display my space. The title of my space is  IOTAnauts . When I type in IOTAnauts in the search for spaces in Discover spaces the only space that gets displayed is IOTAns.  This happen when I am on my desktop using latest version of Chrome with Windows 10.

**Comment by adamkundrat** [comment]
This will be fixed as part of the https://github.com/soonlabs/soonaverse-dao/issues/220
