### ISSUE TITLE
Markdown in Marketplace description 

### ISSUE THREAD

**Issue by SonOfCrypto** [soonlabs/soonaverse-dao#452]
**Describe the bug**
Markdown is not completely working when saving a Marketplace description. For example empty lines.

**To Reproduce**
Try copying some markdown from here https://markdown-it.github.io

**Expected behavior**
All Markdown code is working

**Comment by adamkundrat** [comment]
Agree this should be tweaked.

**Comment by adamkundrat** [comment]
change was reverted. We've to implement Markdown correctly across the whole system.
