### ISSUE TITLE
Be able to add more participants

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#464]
The options to correct your mistake is literally 0 in soonaverse. 
Mistakes happen and mostly for creators that are tired haha 
F.e. I wanted to do a badge for 15 people, so i've created an award for that case. After getting some sleep, i've found out that i've only allowed 10 people <.<
Can we add a option to increase badge participants and also XP, since they are related to each other?

If I want to delete an award, it's not possible.
If I want to add a new award to an existing collection, it's also not possible, if it's in the 24h timerange. 

Like I said, once you did a mistake, it's literally impossible to change it, if you're in a timerush. The only option is to delete/discard/leave it alone and do new things for a different day, which might cause confusion for already communicated dates.

Thx a lot for your work guys <3

**Comment by lazylefteye** [comment]
I don't know how I've added the "Invalid" label and i don't know how i can remove it. Sorry! 

It's not invalid ofc

**Comment by adamkundrat** [comment]
I agree, we need two key improvements to happen on the award and will deliver them soon once our next two key initiatives are complete.

- https://github.com/soonlabs/soonaverse-dao/discussions/351
- https://github.com/soonlabs/soonaverse-dao/discussions/81
