### ISSUE TITLE
Show Spaces instead of collections

### ISSUE THREAD

**Issue by lazylefteye** [soonlabs/soonaverse-dao#466]
It would be pretty nice, if the marketplace could show only spaces and not each collections on it's own.

It starts to be a big mess and a lot of collections are mixing up. 
I f.e. uploaded 4 collections and approved them at nearly the same time (within 1 minute). look how they appeared on the marketplace:
![image](https://user-images.githubusercontent.com/65918138/158886659-47ed0805-340f-405d-b456-a2778a3d3daa.png)

And the filter is: "Sort by recent"

**Comment by adamkundrat** [comment]
I’ll leave this one as an issue. This a valid concern. It’s very hard to go through the list. I know we have few enhancement in works so please move / change as you need to. @humaint

**Comment by humaint** [comment]
you can always filter collections by space, we can't just group collections as there are different use cases for different spaces
