### ISSUE TITLE
Ability to start the process of creating a Collection without the badge

### ISSUE THREAD

**Issue by Florentde29** [soonlabs/soonaverse-dao#469]
**Describe the bug**
Using the MetaMask browser on Android, I'm able to start the process of creating a Collection. It's actually not possible to create it at the end as an error is poping saying a badge is required.

**To Reproduce**
1. Open the browser within the MetaMask app
2. Go to your Soonaverse space
3. Click on the `+` button
4. Collection is listed even if you don't have the badge allowing you to create a Collection

**Expected behavior**
The behavior should be the same as on the desktop browsers, if you don't have the badge allowing you to create a Collection, you should not be able to start the process.

**Screenshots**
![IMG_20220318_043652_2](https://user-images.githubusercontent.com/6325525/158999180-5cd3c7c8-6879-4584-b740-b99d0db2a7e3.jpg)

**Smartphone**
 - Device: Xiaomi Note 10 Lite
 - OS: Android 11 RKQ1.200826.002
 - Browser: MetaMask
 - Version: 4.2.2 (834)

**Comment by JM0unir** [comment]
Replicated on desktop by reducing media screen size to force switch to the mobile version.

![image](https://user-images.githubusercontent.com/39354686/159221052-945a96c6-c281-46e4-9547-540d23947278.png)


- OS: Windows 10
- Browser: Chrome
- Version: 99.0.4844.82
