### ISSUE TITLE
NFT Stats line wrapping

### ISSUE THREAD

**Issue by 2g4y1** [soonlabs/soonaverse-dao#470]
**Describe the bug**
Please fix linewrapping in NFT stats

**To Reproduce**
1. Go to ['here'](https://soonaverse.com/nft/0x811377fec7fb78ab5f9aef12147c8f46376ae3ac)
2. Click on Stats
3. See error at second ability

**Expected behavior**
better placed line break

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/159033760-4b9f041e-bdd6-427a-9de9-060cd548512d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser chrome
 - Version [latest]

**Comment by humaint** [comment]
waiting for desing

**Comment by adamkundrat** [comment]
Btw I've noticed the other day that sometimes the IPFS values within system info looks less ideal. It would break on the next line and "view" hyperlink would be going outside of the input.

**Comment by humaint** [comment]
@Gundavri pls update according to design
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=1705%3A25444

mobile
https://www.figma.com/file/7ER3oGXPRXHCEoUGuUfSLl/Soonaverse-%E2%80%94-Responsive?node-id=1928%3A30159
