### ISSUE TITLE
NFT make a bid popup

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#473]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=1705%3A25444

new designs for biding popup
- initial popup with confirmation
- awaiting payment
- awaiting payment with my transactions
- current highest bid box - my is highest/other user is highest

**Comment by humaint** [comment]
@Gundavri highest priority pls

**Comment by humaint** [comment]
@Gundavri make sure there is enough spacing between box and text (small UI fix)

![SCR-20220327-e2b.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/8d8286db-ff02-48a7-83ee-53d075849883)

**Comment by adamkundrat** [comment]
@Gundavri - I also noticed duration field is missing. Please add the field and make sure it's disabled by default! You don't have to link to a form controller yet. It'll be just to visualize the value. We'll need to eventually determine the final options.

Remove the (8 minutes / 3 days) text from the "Trade Info" title. 

![Screen Shot 2022-03-26 at 5 00 34 PM](https://user-images.githubusercontent.com/130610/160261018-c4969319-99b8-4786-a483-d36b29521b21.png)
