### ISSUE TITLE
Provide a warning on the purchase page to not send funds from an Exchange

### ISSUE THREAD

**Issue by adamkundrat** [soonlabs/soonaverse-dao#478]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/477

<div type='discussions-op-text'>

<sup>Originally posted by **centercirclesolutions** March 21, 2022</sup>
Sending a payment directly from an exchange is a risky and not recommended way to pay for purchases. Many times the exchange will not meet the 4 minute time period and the funds are sent back to the hot wallet address where the user has to make a claim to have the funds re-added to their balance. Some users are still doing this. 

**We should provide a clear message near the address to not send funds from an exchange and only a from a Firefly or TanglePay wallet.**</div>

**Comment by adamkundrat** [comment]
@humaint - let me know how you want to  change the UI and assign back to me

**Comment by humaint** [comment]
waiting for design

**Comment by humaint** [comment]
add text label to checkout
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2238%3A29407
