### ISSUE TITLE
notifications layout

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#482]
implement notifications
- notification dropdown
-- empty state
-- once clicked, notification is read
-- link to the correct record

- notification alert - disappears after few seconds, if clicked, notification is read

![SCR-20220323-m1p.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/f2a25158-6045-4143-a79f-ec011c140535)
![SCR-20220323-m1k.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ffcb2203-94ff-4dd7-83c8-975233345519)

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=1705%3A25444

**Comment by adamkundrat** [comment]
@Gundavri -

Please implement following logic:
- store latest read UID in local cache (setItem/getItem) functions. 
- if getItem in local cache equals to latest notification there is no unread messages
- otherwise count number of messages from top -> latest read and that will be the badge counter
