### ISSUE TITLE
NFT detail - updates to Offer box

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#487]
i would like to clarify the logic and update wordings here
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2890%3A28201

- show empty state when there is/was no auction on this NFT
- change title to Biddings
- 4 columns (From, Bid, Date, Listed By)
- 3 clickable tabs
-- Current bids (displayed only when auction in progress, filter only bids related to the current listing)
-- Past bids (displayed only when auction exists/existed, shows all past bids)
-- My bids (displayed only when you participated in auction, shows all of your bid transactions - same as the popup table)

@adamkundrat FYI

**Comment by adamkundrat** [comment]
@Gundavri - I might have removed the “tab” switcher within HTML the table by mistake. Please just re-add it.
