### ISSUE TITLE
Problem create collection

### ISSUE THREAD

**Issue by Shortcapt** [soonlabs/soonaverse-dao#496]
Hello community ! 

I'm trying to create a new collection on Soonaverse but no button " create collection" on my dashboard... 
I already create a space, proposal and rewards but still no " create collection " ....
Maybe i was missed something.

**Comment by adamkundrat** [comment]
You need to get a badge to create collection. Please reach out to #community-nft-approvers channel on discord and ask them to issue you with badge.
