### ISSUE TITLE
marketplace filter by collection types missing/updated

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#501]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3026%3A31214

![SCR-20220327-dci.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/e04a5164-63be-4047-b7b0-40151bf457c4)

**Comment by adamkundrat** [comment]
@Gundavri - create a filter and assign this issue back to me so I can add logic.

**Comment by adamkundrat** [comment]
fixed.
