### ISSUE TITLE
Listed by when selling missing in Timeline

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#507]
@adamkundrat![SCR-20220327-ejv.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/8e560496-56a7-4d7c-82fb-77830172be8e)

there should be Listed by Soon in the timeline

**Comment by adamkundrat** [comment]
@Gundavri - just show new timeline item if nft.availableFrom is set or nft.auctionFrom is set.

- nft.availableFrom && !!nft.owner -> add top item with text NFT made available for sale.
- nft.auctionFrom && !!nft.owner -> add top item with text NFT made available for auction.

**Comment by humaint** [comment]
![SCR-20220330-sck.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ed9136d7-1b6f-4e27-b255-f682773221f4)

- entry is missing time and date
- should rather say the same thing asi initial listings: Listed by xxx or Made available for auction by xxx

**Comment by Gundavri** [comment]
@humaint  Should the time be when it was listed for sale/auction or when the sale/auction is?

**Comment by humaint** [comment]
there should be start of the auction / start of the sale

**Comment by adamkundrat** [comment]
@humaint - we don’t know the time and date. I’ll need to add it on the back-end.

@Gundavri - please correct the other issue and create a new issue to add time & date that you assign to me.
