### ISSUE TITLE
update NFT cards for trading

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#508]
once the NFT is configured for sale the NFT card info should change:
- fixed price and sale is in progress, see screen
![SCR-20220327-eor.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/5ec8058d-cfc9-4f76-af55-173eaa2f7570)

- fixed price/auction sale starts in x days/today
 ![SCR-20220327-eoj.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/347c77dc-7bc5-487d-b66e-9bf987053242)

- auction alredady available 
 ![SCR-20220327-eoe.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/1d710dab-c424-4029-bb1c-37cc39945c8d)

- not for sale
![SCR-20220327-eow.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/83639056-aba7-4ef8-a952-79057447303f)

**Comment by humaint** [comment]
@Gundavri plus pls update the buy now button, now is alwas just the wallet icon

**Comment by humaint** [comment]
@Gundavri i can see that the card still does look as for sale when auctioned - this is importatn fix

**Comment by adamkundrat** [comment]
I've cleaned it all up. 

@Gundavri - please fix showing of avatar. It's there in TODO
