### ISSUE TITLE
show floor price not no bid

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#509]
![SCR-20220327-ew0.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/a5703ac9-6952-4f3b-880f-45d61b2a6895)![SCR-20220327-ew8.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/5427f864-82f5-4f87-bff1-6b9e5cb8b281)

this box should show floor price (Min Bid) when no bid recieved

**Comment by adamkundrat** [comment]
fixed!
