### ISSUE TITLE
keep only space in the collection preview

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#515]
![SCR-20220329-eak.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/5539ed34-eda8-443c-bad7-740f43d815c7)

same as we have removed the author from collection detail and NFT detail, remove the author here as well

in this case it will say only by Soonaverse!!

**Comment by adamkundrat** [comment]
cleaned up
