### ISSUE TITLE
Listed collections missing when At least one NFT from Collections selected

### ISSUE THREAD

**Issue by humaint** [soonlabs/soonaverse-dao#516]
![SCR-20220329-f0d.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/98a8e63b-e71f-40cc-a2b0-3f4578bbd28b)

similar as we show badges when Space Members with Badge Only selected, we should show selected collections as well

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3025%3A31560

**Comment by adamkundrat** [comment]
I thought that was already there? It was part of the who can buy.

Also, on a separate now shouldn't we have tooltip with actual date on "Starts today" info at the top and make this consistent on actual NFT?

**Comment by adamkundrat** [comment]
@humaint

**Comment by adamkundrat** [comment]
added.
