### ISSUE TITLE
Please show royalty space on the bid page

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#517]
![image](https://user-images.githubusercontent.com/44786846/160538018-fcaf0cc9-a75e-4053-86d8-fa470982d512.png)

**Comment by adamkundrat** [comment]
https://github.com/soonlabs/soonaverse-dao/discussions/559

**Comment by humaint** [comment]
pls add acrrodring to design

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2239%3A31639

![SCR-20220408-hok.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ad9ec98c-e210-48b9-8a8d-d8b9ecc02985)
