### ISSUE TITLE
Generate NFTs button disappears after uploading csv

### ISSUE THREAD

**Issue by MichaelSAXu** [soonlabs/soonaverse-dao#518]
**Describe the bug**
Generate NFT button disappears after 5 seconds after uploading csv.

**To Reproduce**
1. Upload image to nft collection.
2. Upload csv to nft collection
3. Generate NFTs button disappears after 5 seconds

**Expected behavior**
Button should not disappear and be replaced with generate CSV

**Screenshots**
attached

**Desktop (please complete the following information):**
 - OS: [windows 11]

 - Browser [chrome]
 - Version [newest version]

![Screenshot 2022-03-29 194411](https://user-images.githubusercontent.com/17297134/160584551-637e3951-0e81-4886-b6b8-3684386c45ee.png)
![Screenshot 2022-03-29 194301](https://user-images.githubusercontent.com/17297134/160584557-8c6b86e6-3d9d-49f7-a750-924ddef252ca.png)

**Additional context**

**Comment by Gundavri** [comment]
@MichaelSAXu Could not reproduce the bug. Can you attach the video, please?

**Comment by adamunchained** [comment]
part of #568
