### ISSUE TITLE
IP / DMCA issue - unauthorised commercial use of the IOTA Logo

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#520]
Collection https://soonaverse.com/collection/0xbebf30a204f9f1ce9e228c6d2e74e6ce33776388
Sells the IOTA Logo, which is IP of the IOTA Foundation.

This is not allowed due to the logo usage policies of the IOTA Foundation. https://www.iota.org/connect/brand

Please remove the collection

**Comment by adamkundrat** [comment]
collection removed as it breaks T&C
