### ISSUE TITLE
The collection is still availabel but all NFTs are allready sold out.

### ISSUE THREAD

**Issue by DirtyDreamer** [soonlabs/soonaverse-dao#522]
**Describe the bug**
The collection is still availabel but all NFTs are allready sold out.

**To Reproduce**
1. Go to (https://soonaverse.com/collection/0xb3e83df77673a6b9c8706f25412aa6b6df7cbf67)
2. See error

**Expected behavior**
It should say 'sold out'

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]

**Comment by humaint** [comment]
![SCR-20220405-g8u.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/bc892dce-edc1-4863-b13d-5fe47d0f8117)

@adamkundrat FYI

@Gundavri see attached screen with instructions

**Comment by adamkundrat** [comment]
I'll take on this one.
