### ISSUE TITLE
Current Bids not displayed

### ISSUE THREAD

**Issue by ipinsh** [soonlabs/soonaverse-dao#529]
**Describe the bug**
When RETURNING to an NFT with bids, Transactions -> Current Bids shows "no data" even though there are bids.
Reloading the page lets the data show up again.

**To Reproduce**
1. Go to an NFT with bids
2. Click on any link
3. return to the NFT (return button in browser)
4. bids disapear

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Firefix
 - Version: 98.0.1 (64-Bit

**Comment by humaint** [comment]
@adamkundrat can you pls check, I noticed as well. it seems it just takes time to load? Do we know we are waiting for something to show loader?

**Comment by adamkundrat** [comment]
@Gundavri - please investigate. 

Also make sure we show skeleton loading whilst it's loading like we do on another places....i.e. spaces > proposals, etc.
