### ISSUE TITLE
Translation issues in the German translation

### ISSUE THREAD

**Issue by vfinkler** [soonlabs/soonaverse-dao#536]
1. The word "space" has been translated with three different solutions: "space", "Raum" and "Gruppe".  It is confusing when reading it in German. We have to decide on one of the options and change the other strings accordingly.
2. The New Proposal page is only available in English. No translation shown.
3. There are two spelling mistakes (see red circles in the pictures)
![Soonaverse_1](https://user-images.githubusercontent.com/102726363/161020817-b024abe9-8412-4f51-a614-c2a22ffc2c07.png)
![Soonaverse_2](https://user-images.githubusercontent.com/102726363/161020831-393d4c0f-5e59-47be-ab29-6587a82b6db6.png)
4. Strings where the translation is not shown:
On the market place page:
![Soonaverse_3](https://user-images.githubusercontent.com/102726363/161021573-9e618c14-853e-4517-9406-9f3c71bcbebd.png)
![Soonaverse_6](https://user-images.githubusercontent.com/102726363/161022207-b80b1cfe-dae4-4db2-939b-7b25ab6691b4.png)

When creating a new space:
![Soonaverse_4](https://user-images.githubusercontent.com/102726363/161021786-a37728f0-0b4c-4f0d-929b-e8caaf061ba2.png)
![Soonaverse_5](https://user-images.githubusercontent.com/102726363/161022086-5099364f-4975-4119-8de6-a69fa49b56f1.png)

On the "Discover Soonaverse" page:
![Soonaverse_7](https://user-images.githubusercontent.com/102726363/161022492-73ba8ba1-5d38-4e12-9b27-71ed25f0ea4a.png)

**Comment by vfinkler** [comment]
The error message when you try to connect with Metamask but are not logged in is also shown in English. 
![Soonaverse_8](https://user-images.githubusercontent.com/102726363/161024418-a8929f71-1838-4d3e-8020-a36967141585.png)

**Comment by adamkundrat** [comment]
@Gundavri - please fix all these places with i18n flag. Do this against master branch

**Comment by adamkundrat** [comment]
all above can be translate now and show be available for translations
