### ISSUE TITLE
File names broken upload one NFT

### ISSUE THREAD

**Issue by Shortcapt** [soonlabs/soonaverse-dao#537]
Impossible to preview my NFT and upload it on my collection "Shortcube" ... File name problem each time i tried...

**Comment by Shortcapt** [comment]
![Capture d’écran 2022-03-31 132451](https://user-images.githubusercontent.com/102419038/161044590-823a7da2-bdce-4576-990f-6607e5550768.png)
I tried to change browser, change name file etc... but nothing. Thanks a lot for your help Adam !

**Comment by adamkundrat** [comment]
@Gundavri - can you investigate this ASAP and do PR from master for a fix if required

**Comment by adamkundrat** [comment]
filename cant’t contain any spaces. We have improved the validation here and made it consistent with multiple upload.
