### ISSUE TITLE
Members discount not applying

### ISSUE THREAD

**Issue by REMIXMV** [soonlabs/soonaverse-dao#538]
**Describe the bug**
Members discount not being applied properly on the collections.
https://soonaverse.com/space/0xf5e1c00dbfdac2b3b5e60d6fe19978c77dcd3876/collections

**Expected behavior**
When you're a member the discount should be applied properly. thank you

**Screenshots**
![image](https://user-images.githubusercontent.com/99553704/161028945-50ff380a-622d-4d28-8305-4244cb10c45b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] - Firefox
 - Version [e.g. 22] 98.0.2

**Comment by adamkundrat** [comment]
what collection and what member is not getting a discount?

**Comment by REMIXMV** [comment]
Seems like on all the collections, I have them all set as -50%

**Comment by adamkundrat** [comment]
can you give me an example of member and a collection please where it does not work?

**Comment by REMIXMV** [comment]
I'm a member, I should be seeing the -50%?
https://soonaverse.com/member/0xcecd2c1db7f3ba996166ac5a11ef0a260b07efed/activity
https://soonaverse.com/nft/0x5f8e99fa69010c7b8b631f0ee090874ed272ff41

**Comment by adamkundrat** [comment]
hi @REMIXMV - this has been fixed now. You should see your discount within next hour or so.

**Comment by REMIXMV** [comment]
thank you, i love you <3
