### ISSUE TITLE
Account locked when payment encounters network problem timeout

### ISSUE THREAD

**Issue by csxiong** [soonlabs/soonaverse-dao#540]
**Describe the bug**
I was executing a purchase and it timed out due to network. I restarted my computer and Firefly, and when I purchase again, it tells me  "You have currently another order in progress.". My account is Kumasan. The item was purchased by way of a designated buyer. 

**To Reproduce**
1. Go to 'NFT detail page'
2. Click on 'Buy' and pay.
3. Network crack down.
4. Purchasing overdue.
5. Restart my computer and firefly.
6. error 

**Expected behavior**
I can buy .

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Chrome

**Comment by adamkundrat** [comment]
Thanks for reporting this @csxiong 

I’ll investigate and let you know today

**Comment by adamkundrat** [comment]
@csxiong - can you check again? I've not fixed anything but I don't see any NFT being locked for your username 0x0fc1e3b37b572ba462a8d9c7f781af246876ab64

**Comment by csxiong** [comment]
Just checked, the problem still exists.

**Comment by csxiong** [comment]
> 

I feel that this problem is not related to the NFT, because the NFT was later changed to "Not For Sale" by the seller.

**Comment by adamkundrat** [comment]
Hi @csxiong - this should be now fixed.

There has been an issue with script that auto-expires orders where in some scenarios it was not working. This issue was introduced with last update. It should be now fixed.

Can you please confirm? Thanks

**Comment by csxiong** [comment]
yes. Fixed.
