### ISSUE TITLE
Limited edition collection wont allow NFT uploads before publishing.

### ISSUE THREAD

**Issue by Heatho14** [soonlabs/soonaverse-dao#542]
**Describe the bug**
I created [this](https://soonaverse.com/collection/0xda470414482964b832815ec39f08e712a459b3e6) collection today to begin uploading NFT's before publishing.  I filled out the info on the creation page and signed the transaction, I haven't published the collection at all but cannot upload NFT's and get the message "Collection is limited addition. No NFT can be added after approval"

**To Reproduce**
Steps to reproduce the behavior: (not sure if it will re-produce but this is what I did)
1. from [this](https://soonaverse.com/space/0xf45c5c4efb24e85e162e8025f1c45a23932fd47f/overview) space, click "create new" and "Space"

2. Create a new space

3. Verify the wallet (my message ID: 499c333d4d472beba9702c884de86a991f3644456028e14809a7da942ee5f2d0)

4. Create new collection under "Limited Edition"

5. upload 45 PNG images and the .csv file to the multiple image upload section attached is the CSV[soonaverse_NFT_list.csv](https://github.com/soonlabs/soonaverse-dao/files/8394493/soonaverse_NFT_list.csv)

6. See error message "Collection is limited addition. No NFT can be added after approval"

**Expected behavior**
I expected to be able to upload the desired images to my collection prior to publishing the collection and be no longer able to upload images after publishing the collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/73223418/161190419-def60946-ded3-44bd-a370-dd9c8b875055.png)
![image](https://user-images.githubusercontent.com/73223418/161190438-4110564d-52a8-4a08-a111-363fc1397d2f.png)
![image](https://user-images.githubusercontent.com/73223418/161190484-2888b074-5a80-4aa2-83a5-0ab6c5c6bf53.png)
![image](https://user-images.githubusercontent.com/73223418/161190494-4a9dd469-cc60-44a4-bd33-53003605b5ba.png)

**Desktop (please complete the following information):**
 - OS: 
Edition Windows 10 Pro
Version 21H2
Installed on ‎20-‎Aug-‎21
OS build 19044.1586
Experience Windows Feature Experience Pack 120.2212.4170.0

 - Browser: Brave 
 - Version [Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone (please complete the following information):**
 N/A

**Additional context**
@Heatho14 on Soonaverse
Collection: https://soonaverse.com/collection/0xda470414482964b832815ec39f08e712a459b3e6
Space: https://soonaverse.com/space/0x2e2b03c27cbbe33deabded6d04c59da894e1536a/overview

Unsure what more information I can provide, please contact me for more infomation if you need.
FROG DUDE | SLAVA UKRAINI 💙💛#0001 on discord

**Comment by Heatho14** [comment]
To add to this, I was going to create a new collection but leave this up so that the bug could be looked into but I would just post a different collection.  However [this](https://soonaverse.com/collection/0xf2157385e4af279b0f81812b8de88b9fbdaa1518) new collection has done the exact same thing.  Hope this helps.

**Comment by Heatho14** [comment]
> To add to this, I was going to create a new collection but leave this up so that the bug could be looked into but I would just post a different collection. However [this](https://soonaverse.com/collection/0xf2157385e4af279b0f81812b8de88b9fbdaa1518) new collection has done the exact same thing. Hope this helps.

I will be leaving both collection up for investigation :)

**Comment by adamkundrat** [comment]
this has been now fixed, please try again in 10 minutes.
