### ISSUE TITLE
search function marketplace doesn't work smoothly

### ISSUE THREAD

**Issue by adamkundrat** [soonlabs/soonaverse-dao#543]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **Zwoeloem** March 30, 2022</sup>
Hello,

First of all, I love the addition of the marketplace! Awesome job, everything works smooth and instinctively. Except for one function.

When I want to find a certain NFT, lets say Alien#522 . I type in 'Alien' and I then press 'enter' on my keyboard. Nothing happens. To actually get the search function to work I need to click on 'all'/'available'/'on auction'/'owned' for it to update.

My suggestion is to make the search function work by pressing 'enter' on the keyboard. </div>

**Comment by adamkundrat** [comment]
@Gundavri - please check searching on:
- Discover -> all tabs
- Marketplaces -> all tabs 

And make sure it works well. I think there are some edge cases where searching is not triggered (i.e. when you move between tabs, etc.)

**Comment by FJavierGomez** [comment]
Also, sorting by price is not working as expected. It could not be related but just in case. Thanks for the good work!

**Comment by FJavierGomez** [comment]
I don't have permission to see that repo but that's great, thanks 😃

**Comment by adamkundrat** [comment]
ah yeah! not yet, sorry :)

**Comment by adamkundrat** [comment]
Yeah those links are just missing in DEV. I just created those indexes so you should be able to test again.

**Comment by adamkundrat** [comment]
Big bunch of changes were released to improve it. 

In the future, we will be implementing:
- #220 
- new search filters
