### ISSUE TITLE
Sorting NFT's from lowest to highest price does not work

### ISSUE THREAD

**Issue by ivanbeerlama** [soonlabs/soonaverse-dao#546]
**Describe the bug**
Sorting NFT's from lowest to highest price does not work for 'On Auction' and 'Available'

**To Reproduce**
1. Go to 'https://soonaverse.com/market/nfts'
2. Click on 'On Auction of Available'
3. Click on 'Price lowest to highest'
4. NFT's not sorted from lowest to highest

**Expected behavior**
Is should sort from low to high

**Screenshots**

**Devices:**
- OsX an Android

**Comment by adamkundrat** [comment]
this has been now fixed. we're still re-indexing database but should be completed in few hours.
