### ISSUE TITLE
Missing refund of lost auction

### ISSUE THREAD

**Issue by karzz93** [soonlabs/soonaverse-dao#556]
**Describe the bug**
Yesterday I've lost a bid on Soonaverse; 83mi on https://soonaverse.com/nft/0x05ec6e485b5f31b6bd0faa911f852d7f5f59041b
I haven't received the refund yet though: https://explorer.iota.org/mainnet/addr/iota1qqafl0gn4dpv8k2ft53yg4e6k6mk0n3dpqxdf676f6fh9cnwxj6kcz5ka8d

**To Reproduce**
N.A.

**Expected behavior**
I lost the bid, so I expected the refund in firefly.

**Screenshots**
![image](https://user-images.githubusercontent.com/102825153/161316014-5b66922b-a8c4-4531-a751-5cf05f6aba2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version

**Smartphone (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by adamkundrat** [comment]
this has been now resolved. it has been caused by https://github.com/soonlabs/soonaverse-dao/issues/540

you should receive refunds by now.
