### ISSUE TITLE
Missing refund of lost auction

### ISSUE THREAD

**Issue by iotamorons** [soonlabs/soonaverse-dao#557]
Yesterday we have lost an auction on Soonaverse. We did a 160 Mi bid on the NFT https://soonaverse.com/nft/0x05ec6e485b5f31b6bd0faa911f852d7f5f59041b in time, but we didn't win the auction. A 126.00 Mi bid won.

Now we are missing the 160 Mi refund: https://explorer.iota.org/mainnet/addr/iota1qz74m082rc9fjrv2p3h5cyce05zl958uwaya40c2y68034ldjhgjj2fnt96

**To Reproduce**
N.A.

**Expected behavior**
We lost the bid, so I expected the refund in firefly.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Browser: Firefox
Version: Version 98.0.2

Smartphone (please complete the following information):
N.A.

Additional context
N.A.

**Comment by adamkundrat** [comment]
relates to https://github.com/soonlabs/soonaverse-dao/issues/556

This was solved yesterday with this issue: https://github.com/soonlabs/soonaverse-dao/issues/540

We've have few transactions that have to be corrected due #540 issue. We'll fix that and reprocess them within today so you'll get refund.

**Comment by adamkundrat** [comment]
this has been now resolved. it has been caused by https://github.com/soonlabs/soonaverse-dao/issues/540

you should receive refunds by now.
