### ISSUE TITLE
IP / DMCA Request: 

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#562]
SoonLabs responds to notices alleging copyright infringement that comply with the United States Digital Millennium Copyright Act (the “DMCA”).  If you wish to make a DMCA claim, you must provide the following information in writing in your DMCA notice: 

- identify the copyrighted work that you claim has been infringed;
- identify the material claimed to be infringing and where it is located;
- provide reasonably sufficient information to allow SoonLabs to contact you, such as your address, phone number and e-mail address;
- provide a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or law;
- provide a statement, made under penalty of perjury, that the above information is accurate and that you are the copyright owner or are authorized to act on behalf of the owner; and
- provide an electronic or physical signature of a person authorized to act on behalf of the copyright owner.

This spaces use the IOTA Foandation name and / or registered Trademark (IOTA Logo) in a misleading way, please remove them:

https://soonaverse.com/space/0x3656860ce52f77c705074e1f63630d58a8334d8c/overview
https://soonaverse.com/space/0xdf6b66b4123a06d10045be3a06a02b1f32c4fdd9/overview
https://soonaverse.com/space/0x6d8660b7ae3408812789bf1b915a98f5e3422eca/overview

**Comment by adamkundrat** [comment]
spaces have been removed.
