### ISSUE TITLE
Discounts not sending back to the members

### ISSUE THREAD

**Issue by REMIXMV** [soonlabs/soonaverse-dao#563]
**Describe the bug**
I have a "Giveaway" Collections(3) that has -100% discount and its not sending the IOTAs back.

(First three collections)
https://soonaverse.com/space/0xf5e1c00dbfdac2b3b5e60d6fe19978c77dcd3876/collections

**Expected behavior**
Automagical refunds

**Screenshots**

This image is from one of the users that sent an IOTA
![image](https://user-images.githubusercontent.com/99553704/161382155-7eaf6eca-595d-406e-96d4-747d609060c8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox

**Additional context**
there's 3 giveaway collections, currently there's 11 minted between the three and my account kept all the 1Mi and never sent it back to the minter, even though I set the collection settings at -100%

Iota space address : 
iota1qp3gswh98658fat0z89r0rlu8pljcjj8zz2ztflkjk4g8048xu2xkcj4fe9

thank you.

**Comment by adamkundrat** [comment]
There is always a minimum 1Mi that has to be paid. This per design. It's due dust limitation on IOTA. This 1Mi goes to space's wallet. You can refund those ppl manually if you like to. We don't do those refunds.
