### ISSUE TITLE
Double payment caused by delayed payment

### ISSUE THREAD

**Issue by csxiong** [soonlabs/soonaverse-dao#565]
During this purchase, the wallet appeared to pay successfully in the last few seconds, but the purchase page eventually showed a timeout. After another successful purchase, I found two payments of the same amount inside the wallet. I also looked up both message IDs in Tangle Explorer and both were confirmed by the network. So please confirm that this is a double spend and take care of it.

On the product page of the purchase, please note that amount of 350mi: https://soonaverse.com/nft/0xf3954271ed2971c207bd772a6fc72ce99fb69446

Message IDs for both payments.
4d3d4c238793d68c7c7cee600c00677f073133fb593b8b38c4e762c65cfccc63
40d080973b8e8c2c0be5104c303fb3358f9d6f4a2437d4a043f601f377c1a4f0

**Comment by adamkundrat** [comment]
I don't think that's the case. Maybe more UI have acted weird?

Each Message ID refer to a different NFT. Why do you think it's double payment?

- 4d3d4c238793d68c7c7cee600c00677f073133fb593b8b38c4e762c65cfccc63 - was for NFT ID: [https://soonaverse.com/nft/0x64565a48e613bea14ec3b2cc6c2b29d080b184f3](https://soonaverse.com/nft/0x64565a48e613bea14ec3b2cc6c2b29d080b184f3)
- 40d080973b8e8c2c0be5104c303fb3358f9d6f4a2437d4a043f601f377c1a4f0 - was for NFT ID: [https://soonaverse.com/nft/0xf3954271ed2971c207bd772a6fc72ce99fb69446](https://soonaverse.com/nft/0xf3954271ed2971c207bd772a6fc72ce99fb69446)

**Comment by csxiong** [comment]
Yes, it is true that I was wrong. I apologize for the additional trouble I caused you. I am more confident that there is no problem with the process.

**Comment by adamkundrat** [comment]
no don't worry at all. It's good to investigate these.

**Comment by adamkundrat** [comment]
I also think what we need is transactional history under your profile. It's clearly missing. It's already on our backlog. @humaint
