### ISSUE TITLE
Enable public datasets through Big Query

### ISSUE THREAD

**Issue by adamunchained** [soonlabs/soonaverse-dao#571]
Enable public datasets through Big Query

Anyone can start building report on top our datasets

**Comment by m3rlin5ky** [comment]
Hi :)

**Comment by adamunchained** [comment]
@m3rlin5ky - after some careful consideration we will be encourage users to use soonaverse-lib (https://github.com/soonlabs/soonaverse-lib) instead for now to build reports. Big Query data replication is not very consistent.

Let me know what api or data sets are missing in soonaverse-lib and we can add them there.
