### ISSUE TITLE
Allow royalty change but only down

### ISSUE THREAD

**Issue by adamunchained** [soonlabs/soonaverse-dao#577]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/574

<div type='discussions-op-text'>

<sup>Originally posted by **ivanbeerlama** April  4, 2022</sup>
- After sale, allow the royalty to be changed by the creator. But only to a lower percentage.</div>

**Comment by Eyerkaufer** [comment]
Totally support this feature. Otherwise the creator of a NFT can reduce the value of a minted NFT quite a lot (e.g. setting the royalty up to 100%).

**Comment by adamunchained** [comment]
This will come out by Friday. Makes total sense.
