### ISSUE TITLE
IP / DMCA Request: 

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#581]
IOTA Foundation unauthorized commercial copywright use:

**https://soonaverse.com/collection/0x66eb940399fb6f1548f5a9df0ad0329102f1704a**

SoonLabs responds to notices alleging copyright infringement that comply with the United States Digital Millennium Copyright Act (the “DMCA”).  If you wish to make a DMCA claim, you must provide the following information in writing in your DMCA notice: 

- identify the copyrighted work that you claim has been infringed;
- identify the material claimed to be infringing and where it is located;
- provide reasonably sufficient information to allow SoonLabs to contact you, such as your address, phone number and e-mail address;
- provide a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or law;
- provide a statement, made under penalty of perjury, that the above information is accurate and that you are the copyright owner or are authorized to act on behalf of the owner; and
- provide an electronic or physical signature of a person authorized to act on behalf of the copyright owner.

**Comment by adamkundrat** [comment]
rejected.
