### ISSUE TITLE
Add warning that auction can’t be cancelled

### ISSUE THREAD

**Issue by adamunchained** [soonlabs/soonaverse-dao#598]
![7F90D541-2153-48B0-84B8-42A08F369E96](https://user-images.githubusercontent.com/130610/162221546-db82a323-0581-484f-bbbf-3112d140c277.jpeg)

**Comment by humaint** [comment]
@adamkundrat is it common to cancel active auction? or should we just ward user that they can't cancel?

**Comment by adamkundrat** [comment]
I just want to warn the user. Cancelling auction would be a different feature and this is something that I don't want to consider in this this issue.

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2890%3A29419

add confirmation screen after trading setup

**Comment by humaint** [comment]
![SCR-20220426-r6j.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/5c6a88d5-d8c8-40c7-a2c9-67918893b9cf)

@Gundavri we can't show the successful screen during metamask signing, the process is not finished yet

lets just show the banner as part of the trade popup here
![SCR-20220426-rah.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/c954e0aa-13c4-4c51-a502-5047d3731297)

and let's not show the success screen
