### ISSUE TITLE
Remove ilambo for copywrite infringement

### ISSUE THREAD

**Issue by wenlamboNFT** [soonlabs/soonaverse-dao#603]
ilambo collection has stolen all the artwork from wenlambo.one. We own the rights to all the drawings published. Thank you

**Comment by adamkundrat** [comment]
Can you provide following at least some of the following as requested by our T&C: 
- identify the copyrighted work that you claim has been infringed;
- identify the material claimed to be infringing and where it is located;
- provide a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or law;
- provide a statement, made under penalty of perjury, that the above information is accurate and that you are the copyright owner or are authorized to act on behalf of the owner
