### ISSUE TITLE
Refund not Processed

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#604]
**Describe the bug**
https://thetangle.org/address/iota1qqr5nemf5k2r4vlszprfsdjvaxp6jlz72t0lqh8murvknsql7yz95arq954

for https://soonaverse.com/nft/0xac1642f443eb4053e67ccc8745e0179a933e0884

Sent incorrect amount 444 vs 440

**Comment by adamkundrat** [comment]
this has been now fixed.
