### ISSUE TITLE
'Support' button (link to discord channel)

### ISSUE THREAD

**Issue by adamunchained** [soonlabs/soonaverse-dao#605]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/599

<div type='discussions-op-text'>

<sup>Originally posted by **Ronaldvdb** April  7, 2022</sup>
Haya,
Lot's of people with lots of idea's, feedback and problems. Perhaps it's a good idea to create a Soona Support button on every page? With links to discord and github. 

This way people won't get frustrated and lose precious time and energy. This also radiates more confidence and increases the trust bond.

**PS. The link in Soonaverse docs to Soonlabs discord DOES NOT WORK!!</div>

**Comment by adamunchained** [comment]
@TangleAccountant - can you please fix the link to documentation on Discord?

**Comment by TangleAccountant** [comment]
Done!
