### ISSUE TITLE
Creation API Endpoint to query NFT data

### ISSUE THREAD

**Issue by iotabot106** [soonlabs/soonaverse-dao#611]
The goal: Login with proof of a purchased NFT from Soonaverse on my website.

Users can already log in to the site with Metamask on the IOTA EVN test network. In order for them to get access to more content I need to be able to query if they are the owner of a specific NFT.

For the NFT data query I need an API endpoint.

**Comment by iotabot106** [comment]
hello

**Comment by adamunchained** [comment]
Working library has been published. I've to put together readme and documentation, clean up the functions, etc. This is a super early working example. 

See npm: https://www.npmjs.com/package/soonaverse

See jsbin: https://jsbin.com/vusehugawi/edit?html,js,output

You can either include JS script file directly within the browser or use NPM library within your project.
