### ISSUE TITLE
NFT for Transfer is locked

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#617]
**Describe the bug**

The following NFT can not be purchased and says it it locked for multiple times. 

IT has been listed for a transfer to one member

https://soonaverse.com/nft/0x2566cc2802e7e77fc60be0cf92aa0ef0a78451ef

**Comment by Derivs** [comment]
To add some information here. We have tried relisting for different persons to see if they were able to buy, but it keeps providing the same error message that "NFT LOCKED"

**Comment by adamunchained** [comment]
NFT has been released. I'm sorry about the delay that was an internal bug that have left the NFT locked.
