### ISSUE TITLE
[Payment Issue]: No Refund issued for purchase

### ISSUE THREAD

**Issue by centercirclesolutions** [soonlabs/soonaverse-dao#640]
### Discord Name

Wanderer#7876

### Soonaverse Profile Id

0xf67F0a051fd60bC77ac410D26b4cD10E8b4a21d2

### Payment Action

Purchase NFT from Collection

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

FireFly

### Wallet Version

1.4.2

### Payment Sent to Address

iota1qp2smwu280exfuz2l982djzm4tycqr33f644s6u9h5fam0uushpexfu63zk

### Amount Sent

500 Mi

### Payment Message Id

a1f8be6064e827a81c09f361aedf1baa7cda99b19b67aa2888ebd8a433e489bb

### NFT Collection Id

0x287eb6a8c83a352debe57bf0f3a96f30ff734825

### Comments

```shell
I joined Tangleswap Genesis NFT and one of my transaction got confirmed but soonaverse didn't acknowledge it
```

**Comment by adamunchained** [comment]
There were delays with handful transactions and it should be now processed.
