### ISSUE TITLE
Collection release date & time not available

### ISSUE THREAD

**Issue by LordSciFi** [soonlabs/soonaverse-dao#641]
**Describe the bug**
When one wants to create a collection for the next day (in exactly 24h) one can not pick the desired time for the collection to release. The buttons appear grey (see screenshot) for the next day. Also when i created the collection it was 15. April 09:20 CEST. I could only pick 14:25, 14:30, 14:35, 14:40, 14:45, 14:50, 14:55. The further time passed the less options i had e.g at 09:35 i could only pick 14:40, 14:45, 14:50, 14:55. So i waited until 10:00 and suddenly all time options were back available.

The bug occured on 15. April 09:20 CEST.

**To Reproduce**
1. Go to "Collection"
2. Click on "+New Collection"
3. Scroll down to 'Available from'
4. You should see missing date/times for the next day

**Expected behavior**
When i create a collection i expect that i can publish it exactly 24h from now.
The date and exact time should be pickable at any time and not dependable on what time it is.

**Screenshots**
![image](https://user-images.githubusercontent.com/79095057/163676514-32ae6daa-bc43-45f6-a025-a8ca958e25a2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 100.0.4896.88 

**Additional context**

**Comment by adamunchained** [comment]
I think our calendar needs to be improved overall. @humaint can you add this to your backlog.

**Comment by humaint** [comment]
@humaint I agree, the calendar with time is especially difficult to use on mobile. 

but regarding this issue, the time columns are scrollable @LordSciFi
