### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by 0xLon** [soonlabs/soonaverse-dao#645]
### Discord Name

Lon#6438

### Soonaverse Profile Id

0xc33E15c9FE58Bbe234Ed0b8b8c1b8108E0F0b48E

### Payment Action

Purchase NFT from Collection

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

TanglePay

### Wallet Version

1.2.3

### Payment Sent to Address

iota1qz3p2v7uqw3n5k0nyg3jrhvnpj2kywyajavwxwhaxn2fuwg20w6kgacpfwj

### Amount Sent

200

### Payment Message Id

c45006ff38b1d774e026903c613e52420f52c545677ef5a6c2dd7b13e8595ac5

### NFT Collection Id

0x6ff3460398291362dfb323016eafbc627f874e56

### Comments

```shell
I was trying to buy an nft from the iotapes collection. I proceeded as instructed and after the deposit I waited and did not receive. It was reported that the payment had not been made, I lost the amount and I did not receive the nft. Please I need help
my adress: https://thetangle.org/address/iota1qp8y08lrs38m4wk5tz05pqepseq4f2gggh0f0jws63gnfuxkf9qyw3ukeu9
here the transaction: https://thetangle.org/message/c45006ff38b1d774e026903c613e52420f52c545677ef5a6c2dd7b13e8595ac5
```

**Comment by centercirclesolutions** [comment]
This transaction was not refunded

**Comment by adamunchained** [comment]
This has been refunded and other few failed transactions. We'll be improving process further when we have such huge peak to handle the scalability better.

**Comment by 0xLon** [comment]
> This has been refunded and other few failed transactions. We'll be improving process further when we have such huge peak to handle the scalability better.

Thank you so much ! So, i'll be able to buy again?

**Comment by centercirclesolutions** [comment]
You can purchase any NFT that is available.
