### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by KK089** [soonlabs/soonaverse-dao#648]
### Discord Name

@KK#0101

### Soonaverse Profile Id

0xAa7DB118975E0d2885792AE3dBdE7e3eeF0A0638

### Payment Action

Purchase NFT from Collection

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

TanglePay

### Wallet Version

1.2.0

### Payment Sent to Address

iota1qzg54aavtkemxe8m222us5xkwrnm6pa4mde3ntvr54dtl4crctf75u54z90

### Amount Sent

500 Mi

### Payment Message Id

00c9bf8f60055b7a25a4ad41085a2c0b302d9c50b976dae060dcf1be88a89f6e

### Comments

```shell
I am unable to locate NFT ID numbers; I was trying to buy a TangleSwap NFT as they were first made available for sale 4/15/22 0600 PST.
I sent payment from TanglePay. 500Mi was sent from my wallet but I did not receive the NFT.
```

**Comment by adamunchained** [comment]
You were refunded. There were few delays yesterday and this one of them: https://thetangle.org/message/00c9bf8f60055b7a25a4ad41085a2c0b302d9c50b976dae060dcf1be88a89f6e

**Comment by KK089** [comment]
YES! and response time was so fast. Thank you!!!

**Comment by adamunchained** [comment]
No worries, hope we can slowly avoid these issues into the future.
