### ISSUE TITLE
IP / DMCA Request:  IOTA, Assembly, Shimmer logo

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#650]
Space https://soonaverse.com/collection/0x20908c2190d662f28ab477511f29c817f8a1d63a 
sells IOTA logos for profit, does not follow the IOTA logo usage policy as laid out here: https://www.iota.org/connect/brand

This is non permissioned commercial use of the Trademarks of the IOTA Foundation.

SoonLabs responds to notices alleging copyright infringement that comply with the United States Digital Millennium Copyright Act (the “DMCA”).  If you wish to make a DMCA claim, you must provide the following information in writing in your DMCA notice: 

- identify the copyrighted work that you claim has been infringed;
- identify the material claimed to be infringing and where it is located;
- provide a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or law;
- provide a statement, made under penalty of perjury, that the above information is accurate and that you are the copyright owner or are authorized to act on behalf of the owner

**Comment by adamunchained** [comment]
rejected
