### ISSUE TITLE
Very annoying dissaperance of the images! (for creators)

### ISSUE THREAD

**Issue by LordSciFi** [soonlabs/soonaverse-dao#658]
**Describe the bug**
When a creator uploads (veryfied with several others) his files for the NFTs, then loads in the .CSV and starts to check if all the properties are correct, the elemnts suddenly dissapear. The Images are (mostly) still there and one has to reupload the .CSV to be able to continue checking the properties. This is super annoying and makes (at least me) insecure if everything is correct! It would be fine if one would only have to upload the .CSV a second time but one needs to upload it many, many times to really check the properties, the elements (NFTs) dissapear mostly after a few seconds an then we have to reupload the .CSV.

Today (8th or 9th collection i'm creating) for the first time it was not just the .CSV/elements dissapearing but also the images and i had to re upload all the big files (.webp) again and then reupload the .CSV several times!

**To Reproduce**
1. Go to 'Create NFT'
2. Click on 'Upload Multiple'
3. Upload the images for the NFTs and the .CSV
4. The .CSV/elements dissapear and sometimes also the images and one has to redo the whole process or upload the .CSV several times to check the properties

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/79095057/163959180-90b5dbda-fab4-454d-b90f-15e2fcb6c5d1.png)
In this screen shot the images are still here but it shows 0/500 uploads.

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version Version 100.0.4896.88

**Additional context**

**Comment by adamunchained** [comment]
There is an open issue for this: https://github.com/soonlabs/soonaverse-dao/issues/568

Closing this one as duplicate.
