### ISSUE TITLE
Cant participate in a vote even if part of the space since long time

### ISSUE THREAD

**Issue by Phyloiota** [soonlabs/soonaverse-dao#677]
**Describe the bug**
The new proposal on the TFT space is up for a vote but it won't let me participate:
![image](https://user-images.githubusercontent.com/77154511/164893915-44a23e42-2207-4d59-90cc-1598976510e7.png)
https://soonaverse.com/proposal/0xa6552bcef6a53a4bc46fbd9d7e512e5710177588/overview

While i am a long term member of the space
![image](https://user-images.githubusercontent.com/77154511/164893950-23c3d7a8-d16b-4fb5-8f46-41d25f143055.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
Are you part of their space? This is a current limitation. You have to be part of the space to vote.
