### ISSUE TITLE
Need for an error/rejection message when uploading non-accepted file formats to avatar/banner.

### ISSUE THREAD

**Issue by camusdefinitely** [soonlabs/soonaverse-dao#86]
I had accidentally downloaded an image from chrome as a Chrome HTML Document (.webp) instead of .jpg. In trying to upload the image, I tried 4-5 times without realizing the issue was with the file format, not soonaverse.

Some type of rejection or error message when the file is rejected either based on size or file format would could be helpful to users.

**Comment by adamkundrat** [comment]
Backend does not support "image/gif" but frontend allows it. We will tweak front-end.

**Comment by adamkundrat** [comment]
Added description and disallowed gif on client side as they're not supported on the backend.
